// Real API responses captured on 2026-10-01 from the Development API (Task 5.2): Skipped with no Email:BrevoApiKey,
// Failed with an invalid key and Email:RedirectAllTo set (Brevo answered 401; nothing was sent).
// Generated by the Task 5.2 capture script (make_fixtures.py); do not edit by hand. Recapture after a contract change.
import type { NotificationLogDto } from '../../api/types'

/** An approval email with email disabled. */
export const SKIPPED_APPROVED: NotificationLogDto[] = [
  {
    "id": 2,
    "kind": "Approved",
    "channel": "Email",
    "status": "Skipped",
    "recipient": "lecturer@campusspace.local",
    "redirected": false,
    "attempts": 1,
    "createdAt": "2026-10-01T02:20:37.851385Z",
    "lastAttemptAt": "2026-10-01T02:20:41.800685Z",
    "sentAt": null,
    "error": "Email is not configured (Email:BrevoApiKey is empty)"
  }
]

/** An officer's rejection email with email disabled. */
export const SKIPPED_REJECTED: NotificationLogDto[] = [
  {
    "id": 1,
    "kind": "Rejected",
    "channel": "Email",
    "status": "Skipped",
    "recipient": "lecturer@campusspace.local",
    "redirected": false,
    "attempts": 1,
    "createdAt": "2026-10-01T02:20:26.660303Z",
    "lastAttemptAt": "2026-10-01T02:20:26.800695Z",
    "sentAt": null,
    "error": "Email is not configured (Email:BrevoApiKey is empty)"
  }
]

/** An officer's rejection email that Brevo refused (invalid key), redirected. */
export const FAILED_REJECTED: NotificationLogDto[] = [
  {
    "id": 3,
    "kind": "Rejected",
    "channel": "Email",
    "status": "Failed",
    "recipient": "lecturer@campusspace.local",
    "redirected": true,
    "attempts": 1,
    "createdAt": "2026-10-01T02:20:59.649141Z",
    "lastAttemptAt": "2026-10-01T02:21:01.184834Z",
    "sentAt": null,
    "error": "HTTP 401 (unauthorized)"
  }
]
