// Real API responses captured on 2026-09-29 from the Development API with stub agents (Task 3.5).
// Generated by /tmp/checklist-3.5/make_fixtures.py; do not edit by hand.

/// PendingApproval with latestProposal (A301, LKR 5,500, Draft).
const pendingProposalJson = r'''{
  "id": 42,
  "purpose": "Robotics Club Arduino workshop",
  "status": "PendingApproval",
  "attendees": 45,
  "requestedStart": "2026-11-19T08:30:00Z",
  "requestedEnd": "2026-11-19T11:30:00Z",
  "budgetLkr": 8000.0,
  "notes": "prefer near the main building",
  "requester": {
    "id": 1,
    "name": "Kavindi Perera",
    "email": "kavindi@campusspace.local",
    "role": "Student"
  },
  "club": {
    "id": 1,
    "name": "Robotics Club"
  },
  "requiredFeatures": [
    {
      "code": "computers",
      "name": "Computers"
    },
    {
      "code": "projector",
      "name": "Projector"
    }
  ],
  "equipment": [
    {
      "typeId": 1,
      "typeCode": "MIC-WIRELESS",
      "typeName": "Wireless microphone",
      "quantity": 2
    },
    {
      "typeId": 4,
      "typeCode": "PROJ-PORTABLE",
      "typeName": "Portable projector",
      "quantity": 1
    }
  ],
  "history": [
    {
      "fromStatus": null,
      "toStatus": "Submitted",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:35:49.682726Z"
    },
    {
      "fromStatus": "Submitted",
      "toStatus": "AgentProcessing",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:35:49.70113Z"
    },
    {
      "fromStatus": "AgentProcessing",
      "toStatus": "PendingApproval",
      "changedById": null,
      "changedByName": null,
      "reason": null,
      "changedAt": "2026-09-29T06:35:52.308442Z"
    }
  ],
  "latestProposal": {
    "runId": "8f5129c0-3a99-40a0-831a-0d7791c7ebe8",
    "revisionNo": 1,
    "roomId": 1,
    "roomCode": "A301",
    "roomName": "Computer Lab A301",
    "quoteId": 13,
    "total": 5500.0,
    "exempt": false,
    "quoteStatus": "Draft"
  },
  "cancelledAt": null,
  "isLateCancellation": false,
  "cancelledByOfficer": false,
  "createdAt": "2026-09-29T06:35:49.710851Z",
  "updatedAt": "2026-09-29T06:35:52.308445Z"
}''';

/// The same request approved (Issued quote).
const approvedDetailJson = r'''{
  "id": 42,
  "purpose": "Robotics Club Arduino workshop",
  "status": "Approved",
  "attendees": 45,
  "requestedStart": "2026-11-19T08:30:00Z",
  "requestedEnd": "2026-11-19T11:30:00Z",
  "budgetLkr": 8000.0,
  "notes": "prefer near the main building",
  "requester": {
    "id": 1,
    "name": "Kavindi Perera",
    "email": "kavindi@campusspace.local",
    "role": "Student"
  },
  "club": {
    "id": 1,
    "name": "Robotics Club"
  },
  "requiredFeatures": [
    {
      "code": "computers",
      "name": "Computers"
    },
    {
      "code": "projector",
      "name": "Projector"
    }
  ],
  "equipment": [
    {
      "typeId": 1,
      "typeCode": "MIC-WIRELESS",
      "typeName": "Wireless microphone",
      "quantity": 2
    },
    {
      "typeId": 4,
      "typeCode": "PROJ-PORTABLE",
      "typeName": "Portable projector",
      "quantity": 1
    }
  ],
  "history": [
    {
      "fromStatus": null,
      "toStatus": "Submitted",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:35:49.682726Z"
    },
    {
      "fromStatus": "Submitted",
      "toStatus": "AgentProcessing",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:35:49.70113Z"
    },
    {
      "fromStatus": "AgentProcessing",
      "toStatus": "PendingApproval",
      "changedById": null,
      "changedByName": null,
      "reason": null,
      "changedAt": "2026-09-29T06:35:52.308442Z"
    },
    {
      "fromStatus": "PendingApproval",
      "toStatus": "Approved",
      "changedById": 4,
      "changedByName": "Mr. Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:35:53.656418Z"
    }
  ],
  "latestProposal": {
    "runId": "8f5129c0-3a99-40a0-831a-0d7791c7ebe8",
    "revisionNo": 1,
    "roomId": 1,
    "roomCode": "A301",
    "roomName": "Computer Lab A301",
    "quoteId": 13,
    "total": 5500.0,
    "exempt": false,
    "quoteStatus": "Issued"
  },
  "cancelledAt": null,
  "isLateCancellation": false,
  "cancelledByOfficer": false,
  "createdAt": "2026-09-29T06:35:49.710851Z",
  "updatedAt": "2026-09-29T06:35:53.657477Z"
}''';

/// Its Issued quotation.
const issuedQuotationJson = r'''{
  "id": 13,
  "requestId": 42,
  "status": "Issued",
  "lines": [
    {
      "kind": "Room",
      "description": "Computer lab A301, 3 h @ LKR 1,500",
      "qty": 3.0,
      "unitPrice": 1500.0,
      "lineTotal": 4500.0
    },
    {
      "kind": "Equipment",
      "description": "Wireless microphone x2 @ LKR 500",
      "qty": 2.0,
      "unitPrice": 500.0,
      "lineTotal": 1000.0
    }
  ],
  "subtotal": 5500.0,
  "discount": 0.0,
  "discountReason": null,
  "exempt": false,
  "total": 5500.0,
  "currency": "LKR"
}''';

/// AgentProcessing right after an officer's Request revision.
const revisingDetailJson = r'''{
  "id": 37,
  "purpose": "Robotics workshop",
  "status": "AgentProcessing",
  "attendees": 45,
  "requestedStart": "2026-11-18T03:30:00Z",
  "requestedEnd": "2026-11-18T06:30:00Z",
  "budgetLkr": 8000.0,
  "notes": null,
  "requester": {
    "id": 1,
    "name": "Kavindi Perera",
    "email": "kavindi@campusspace.local"
  },
  "club": {
    "id": 1,
    "name": "Robotics Club"
  },
  "requiredFeatures": [
    {
      "code": "computers",
      "name": "Computers"
    },
    {
      "code": "projector",
      "name": "Projector"
    }
  ],
  "equipment": [
    {
      "typeId": 1,
      "typeCode": "MIC-WIRELESS",
      "typeName": "Wireless microphone",
      "quantity": 2
    },
    {
      "typeId": 4,
      "typeCode": "PROJ-PORTABLE",
      "typeName": "Portable projector",
      "quantity": 1
    }
  ],
  "history": [
    {
      "fromStatus": null,
      "toStatus": "Submitted",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:14:59.516712Z"
    },
    {
      "fromStatus": "Submitted",
      "toStatus": "AgentProcessing",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:14:59.516899Z"
    },
    {
      "fromStatus": "AgentProcessing",
      "toStatus": "PendingApproval",
      "changedById": null,
      "changedByName": null,
      "reason": null,
      "changedAt": "2026-09-29T06:15:00.814246Z"
    },
    {
      "fromStatus": "PendingApproval",
      "toStatus": "RevisionRequested",
      "changedById": 4,
      "changedByName": "Mr. Perera",
      "reason": "Use a lab in the New Building",
      "changedAt": "2026-09-29T06:15:01.642335Z"
    },
    {
      "fromStatus": "RevisionRequested",
      "toStatus": "AgentProcessing",
      "changedById": 4,
      "changedByName": "Mr. Perera",
      "reason": "Use a lab in the New Building",
      "changedAt": "2026-09-29T06:15:01.642336Z"
    }
  ],
  "latestProposal": null,
  "cancelledAt": null,
  "isLateCancellation": false,
  "cancelledByOfficer": false,
  "createdAt": "2026-09-29T06:14:59.51694Z",
  "updatedAt": "2026-09-29T06:15:01.642338Z"
}''';

/// Rejected by the officer, with the reason.
const rejectedDetailJson = r'''{
  "id": 37,
  "purpose": "Robotics workshop",
  "status": "Rejected",
  "attendees": 45,
  "requestedStart": "2026-11-18T03:30:00Z",
  "requestedEnd": "2026-11-18T06:30:00Z",
  "budgetLkr": 8000.0,
  "notes": null,
  "requester": {
    "id": 1,
    "name": "Kavindi Perera",
    "email": "kavindi@campusspace.local"
  },
  "club": {
    "id": 1,
    "name": "Robotics Club"
  },
  "requiredFeatures": [
    {
      "code": "computers",
      "name": "Computers"
    },
    {
      "code": "projector",
      "name": "Projector"
    }
  ],
  "equipment": [
    {
      "typeId": 1,
      "typeCode": "MIC-WIRELESS",
      "typeName": "Wireless microphone",
      "quantity": 2
    },
    {
      "typeId": 4,
      "typeCode": "PROJ-PORTABLE",
      "typeName": "Portable projector",
      "quantity": 1
    }
  ],
  "history": [
    {
      "fromStatus": null,
      "toStatus": "Submitted",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:14:59.516712Z"
    },
    {
      "fromStatus": "Submitted",
      "toStatus": "AgentProcessing",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:14:59.516899Z"
    },
    {
      "fromStatus": "AgentProcessing",
      "toStatus": "PendingApproval",
      "changedById": null,
      "changedByName": null,
      "reason": null,
      "changedAt": "2026-09-29T06:15:00.814246Z"
    },
    {
      "fromStatus": "PendingApproval",
      "toStatus": "RevisionRequested",
      "changedById": 4,
      "changedByName": "Mr. Perera",
      "reason": "Use a lab in the New Building",
      "changedAt": "2026-09-29T06:15:01.642335Z"
    },
    {
      "fromStatus": "RevisionRequested",
      "toStatus": "AgentProcessing",
      "changedById": 4,
      "changedByName": "Mr. Perera",
      "reason": "Use a lab in the New Building",
      "changedAt": "2026-09-29T06:15:01.642336Z"
    },
    {
      "fromStatus": "AgentProcessing",
      "toStatus": "PendingApproval",
      "changedById": null,
      "changedByName": null,
      "reason": null,
      "changedAt": "2026-09-29T06:15:03.819796Z"
    },
    {
      "fromStatus": "PendingApproval",
      "toStatus": "Rejected",
      "changedById": 4,
      "changedByName": "Mr. Perera",
      "reason": "The New Building labs are reserved for exams that week.",
      "changedAt": "2026-09-29T06:15:04.850607Z"
    }
  ],
  "latestProposal": null,
  "cancelledAt": null,
  "isLateCancellation": false,
  "cancelledByOfficer": false,
  "createdAt": "2026-09-29T06:14:59.51694Z",
  "updatedAt": "2026-09-29T06:15:04.850611Z"
}''';

/// Rejected by the system at approval (actor null).
const closedAutomaticallyJson = r'''{
  "id": 41,
  "purpose": "Drama rehearsal",
  "status": "Rejected",
  "attendees": 30,
  "requestedStart": "2026-11-20T08:30:00Z",
  "requestedEnd": "2026-11-20T10:30:00Z",
  "budgetLkr": 5000.0,
  "notes": null,
  "requester": {
    "id": 7,
    "name": "Nethmi Rajapaksa",
    "email": "nethmi@campusspace.local"
  },
  "club": {
    "id": 2,
    "name": "Drama Society"
  },
  "requiredFeatures": [
    {
      "code": "projector",
      "name": "Projector"
    }
  ],
  "equipment": [
    {
      "typeId": 1,
      "typeCode": "MIC-WIRELESS",
      "typeName": "Wireless microphone",
      "quantity": 1
    }
  ],
  "history": [
    {
      "fromStatus": null,
      "toStatus": "Submitted",
      "changedById": 7,
      "changedByName": "Nethmi Rajapaksa",
      "reason": null,
      "changedAt": "2026-09-29T06:18:00.905813Z"
    },
    {
      "fromStatus": "Submitted",
      "toStatus": "AgentProcessing",
      "changedById": 7,
      "changedByName": "Nethmi Rajapaksa",
      "reason": null,
      "changedAt": "2026-09-29T06:18:00.906312Z"
    },
    {
      "fromStatus": "AgentProcessing",
      "toStatus": "PendingApproval",
      "changedById": null,
      "changedByName": null,
      "reason": null,
      "changedAt": "2026-09-29T06:18:03.748205Z"
    },
    {
      "fromStatus": "PendingApproval",
      "toStatus": "Rejected",
      "changedById": null,
      "changedByName": null,
      "reason": "The requested time is no longer valid: Can be booked at most 30 days ahead (as of submission)",
      "changedAt": "2026-09-29T06:18:04.663467Z"
    }
  ],
  "latestProposal": null,
  "cancelledAt": null,
  "isLateCancellation": false,
  "cancelledByOfficer": false,
  "createdAt": "2026-09-29T06:18:00.906658Z",
  "updatedAt": "2026-09-29T06:18:04.663471Z"
}''';

/// AgentFailed (agent service stopped).
const agentFailedDetailJson = r'''{
  "id": 40,
  "purpose": "Robotics workshop",
  "status": "AgentFailed",
  "attendees": 45,
  "requestedStart": "2026-11-16T08:30:00Z",
  "requestedEnd": "2026-11-16T10:30:00Z",
  "budgetLkr": 8000.0,
  "notes": null,
  "requester": {
    "id": 8,
    "name": "Tharindu Wickramasinghe",
    "email": "tharindu@campusspace.local"
  },
  "club": {
    "id": 3,
    "name": "IEEE Student Branch"
  },
  "requiredFeatures": [
    {
      "code": "computers",
      "name": "Computers"
    },
    {
      "code": "projector",
      "name": "Projector"
    }
  ],
  "equipment": [
    {
      "typeId": 1,
      "typeCode": "MIC-WIRELESS",
      "typeName": "Wireless microphone",
      "quantity": 2
    },
    {
      "typeId": 4,
      "typeCode": "PROJ-PORTABLE",
      "typeName": "Portable projector",
      "quantity": 1
    }
  ],
  "history": [
    {
      "fromStatus": null,
      "toStatus": "Submitted",
      "changedById": 8,
      "changedByName": "Tharindu Wickramasinghe",
      "reason": null,
      "changedAt": "2026-09-29T06:15:14.608097Z"
    },
    {
      "fromStatus": "Submitted",
      "toStatus": "AgentProcessing",
      "changedById": 8,
      "changedByName": "Tharindu Wickramasinghe",
      "reason": null,
      "changedAt": "2026-09-29T06:15:14.608212Z"
    },
    {
      "fromStatus": "AgentProcessing",
      "toStatus": "AgentFailed",
      "changedById": null,
      "changedByName": null,
      "reason": "Agent service unreachable (last error: network error)",
      "changedAt": "2026-09-29T06:17:15.725897Z"
    }
  ],
  "latestProposal": null,
  "cancelledAt": null,
  "isLateCancellation": false,
  "cancelledByOfficer": false,
  "createdAt": "2026-09-29T06:15:14.608246Z",
  "updatedAt": "2026-09-29T06:17:15.726089Z"
}''';
