// Real API responses captured on 2026-10-01 from the Development API (Task 5.1), stub and LLM runs from Phases 3–4.
// Generated by /tmp/checklist-5.1/make_fixtures.py from capture.sh's output; do not edit by hand.
import type { AgentRunDetailDto, AgentRunListItemDto, AgentRunMetricsDto, PagedResult } from '../../api/types'

/** GET /api/agent-runs/metrics?from=2026-09-25&to=2026-10-01 */
export const METRICS: AgentRunMetricsDto = {
  "from": "2026-09-25",
  "to": "2026-10-01",
  "runs": {
    "total": 20,
    "byStatus": {
      "Queued": 0,
      "Running": 0,
      "AwaitingApproval": 2,
      "Resuming": 0,
      "Completed": 3,
      "Rejected": 4,
      "Failed": 8,
      "Cancelled": 3
    },
    "inProgress": 0,
    "finished": 20,
    "reachedGate": 15,
    "failedBeforeGate": 5,
    "successRate": 0.75,
    "reachedGateProcessing": {
      "runs": 15,
      "withoutSteps": 0,
      "avgMs": 3146,
      "p95Ms": 16356
    },
    "failedBeforeGateProcessing": {
      "runs": 2,
      "withoutSteps": 3,
      "avgMs": 36,
      "p95Ms": 37
    },
    "runsWithUsage": 3,
    "totalTokens": 17811,
    "avgTokensPerRun": 5937,
    "llmAttemptedRuns": 3,
    "fallbackRuns": 0,
    "fallbackRate": 0
  },
  "agents": [
    {
      "agent": "supervisor",
      "steps": 20,
      "avgMs": 1701,
      "p95Ms": 7229,
      "failedSteps": 0,
      "failureRate": 0,
      "llmSteps": 5,
      "llmShare": 0.25,
      "skippedSteps": 0,
      "llmAttemptedSteps": 5,
      "fallbackSteps": 0,
      "fallbackRate": 0,
      "stepsWithUsage": 5,
      "totalTokens": 8449,
      "avgTokensPerStep": 1689.8
    },
    {
      "agent": "venue_matching",
      "steps": 20,
      "avgMs": 484,
      "p95Ms": 3153,
      "failedSteps": 0,
      "failureRate": 0,
      "llmSteps": 3,
      "llmShare": 0.15,
      "skippedSteps": 0,
      "llmAttemptedSteps": 3,
      "fallbackSteps": 0,
      "fallbackRate": 0,
      "stepsWithUsage": 3,
      "totalTokens": 7280,
      "avgTokensPerStep": 2426.7
    },
    {
      "agent": "equipment_allocation",
      "steps": 18,
      "avgMs": 157,
      "p95Ms": 430,
      "failedSteps": 0,
      "failureRate": 0,
      "llmSteps": 1,
      "llmShare": 0.0556,
      "skippedSteps": 0,
      "llmAttemptedSteps": 1,
      "fallbackSteps": 0,
      "fallbackRate": 0,
      "stepsWithUsage": 1,
      "totalTokens": 2082,
      "avgTokensPerStep": 2082
    },
    {
      "agent": "policy_cost",
      "steps": 20,
      "avgMs": 12,
      "p95Ms": 35,
      "failedSteps": 0,
      "failureRate": 0,
      "llmSteps": 0,
      "llmShare": 0,
      "skippedSteps": 0,
      "llmAttemptedSteps": 0,
      "fallbackSteps": 0,
      "fallbackRate": null,
      "stepsWithUsage": 0,
      "totalTokens": 0,
      "avgTokensPerStep": null
    },
    {
      "agent": "validate",
      "steps": 20,
      "avgMs": 25,
      "p95Ms": 60,
      "failedSteps": 0,
      "failureRate": 0,
      "llmSteps": 0,
      "llmShare": 0,
      "skippedSteps": 0,
      "llmAttemptedSteps": 0,
      "fallbackSteps": 0,
      "fallbackRate": null,
      "stepsWithUsage": 0,
      "totalTokens": 0,
      "avgTokensPerStep": null
    },
    {
      "agent": "finalize",
      "steps": 6,
      "avgMs": 10,
      "p95Ms": 13,
      "failedSteps": 2,
      "failureRate": 0.3333,
      "llmSteps": 0,
      "llmShare": 0,
      "skippedSteps": 0,
      "llmAttemptedSteps": 0,
      "fallbackSteps": 0,
      "fallbackRate": null,
      "stepsWithUsage": 0,
      "totalTokens": 0,
      "avgTokensPerStep": null
    }
  ]
}

/** GET /api/agent-runs?from=2026-09-25&to=2026-10-01&page=1&pageSize=20 */
export const RUNS_PAGE: PagedResult<AgentRunListItemDto> = {
  "items": [
    {
      "id": "53b8541b-7448-41cf-8068-8a52d3867f99",
      "requestId": 45,
      "purpose": "4.3 equipment",
      "revisionNo": 1,
      "status": "Rejected",
      "model": "planner=gemini-3.5-flash; venue_matching+equipment_allocation=gemini-3.5-flash-lite, others=stub",
      "startedAt": "2026-09-29T16:36:17.226698Z",
      "completedAt": "2026-09-29T16:52:15.372343Z",
      "durationMs": 11001,
      "failureReason": null,
      "stepCount": 5,
      "toolCallCount": 12,
      "totalTokens": 5840,
      "anyFallback": false,
      "createdAt": "2026-09-29T16:36:17.074314Z"
    },
    {
      "id": "fd758455-acbd-4e8f-8ae4-d1ae210a11fe",
      "requestId": 44,
      "purpose": "4.2 venue",
      "revisionNo": 2,
      "status": "Rejected",
      "model": "planner=gemini-3.5-flash; venue_matching=gemini-3.5-flash-lite, others=stub",
      "startedAt": "2026-09-29T15:50:27.677566Z",
      "completedAt": "2026-09-29T15:54:05.353118Z",
      "durationMs": 162075,
      "failureReason": null,
      "stepCount": 10,
      "toolCallCount": 21,
      "totalTokens": 7470,
      "anyFallback": false,
      "createdAt": "2026-09-29T15:50:27.54418Z"
    },
    {
      "id": "87d55b9a-37ac-493a-9851-cc03beb6eded",
      "requestId": 43,
      "purpose": "4.1 planner",
      "revisionNo": 2,
      "status": "Rejected",
      "model": "planner=gemini-3.5-flash; workers=stub",
      "startedAt": "2026-09-29T14:58:52.846141Z",
      "completedAt": "2026-09-29T15:05:10.387323Z",
      "durationMs": 337468,
      "failureReason": null,
      "stepCount": 10,
      "toolCallCount": 21,
      "totalTokens": 4501,
      "anyFallback": false,
      "createdAt": "2026-09-29T14:58:52.714911Z"
    },
    {
      "id": "8f5129c0-3a99-40a0-831a-0d7791c7ebe8",
      "requestId": 42,
      "purpose": "Robotics Club Arduino workshop",
      "revisionNo": 1,
      "status": "Completed",
      "model": "stub",
      "startedAt": "2026-09-29T06:35:49.771626Z",
      "completedAt": "2026-09-29T06:35:53.657421Z",
      "durationMs": 3364,
      "failureReason": null,
      "stepCount": 6,
      "toolCallCount": 15,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T06:35:49.710851Z"
    },
    {
      "id": "8153a27b-08be-40a8-9f6d-525fb794dac3",
      "requestId": 41,
      "purpose": "Drama rehearsal",
      "revisionNo": 1,
      "status": "Failed",
      "model": "stub",
      "startedAt": "2026-09-29T06:18:00.921757Z",
      "completedAt": "2026-09-29T06:18:04.66241Z",
      "durationMs": 2824,
      "failureReason": "Can be booked at most 30 days ahead (as of submission)",
      "stepCount": 6,
      "toolCallCount": 15,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T06:18:00.906658Z"
    },
    {
      "id": "c43f8fec-7f4c-4604-b599-848f8eb1848f",
      "requestId": 40,
      "purpose": "Robotics workshop",
      "revisionNo": 2,
      "status": "AwaitingApproval",
      "model": "stub",
      "startedAt": "2026-09-29T06:17:17.354513Z",
      "completedAt": null,
      "durationMs": 1387,
      "failureReason": null,
      "stepCount": 5,
      "toolCallCount": 12,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T06:17:17.342397Z"
    },
    {
      "id": "864acbac-e9ef-44c9-be78-ba355a7d8cac",
      "requestId": 40,
      "purpose": "Robotics workshop",
      "revisionNo": 1,
      "status": "Failed",
      "model": null,
      "startedAt": null,
      "completedAt": "2026-09-29T06:17:15.725857Z",
      "durationMs": null,
      "failureReason": "Agent service unreachable (last error: network error)",
      "stepCount": 0,
      "toolCallCount": 0,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T06:15:14.608246Z"
    },
    {
      "id": "47ad40de-e9ef-4e83-86bd-6345a3c438c5",
      "requestId": 39,
      "purpose": "Robotics workshop",
      "revisionNo": 2,
      "status": "AwaitingApproval",
      "model": "stub",
      "startedAt": "2026-09-29T06:15:11.381264Z",
      "completedAt": null,
      "durationMs": 1427,
      "failureReason": null,
      "stepCount": 5,
      "toolCallCount": 12,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T06:15:11.370562Z"
    },
    {
      "id": "179f46ba-a165-43f9-994f-ec18d2ede940",
      "requestId": 39,
      "purpose": "Robotics workshop",
      "revisionNo": 1,
      "status": "Failed",
      "model": "stub",
      "startedAt": "2026-09-29T06:15:07.651191Z",
      "completedAt": "2026-09-29T06:15:11.358623Z",
      "durationMs": 2176,
      "failureReason": "Final re-check failed: V02: Room A301 is no longer free for the requested window",
      "stepCount": 6,
      "toolCallCount": 15,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T06:15:07.64346Z"
    },
    {
      "id": "54ffe125-4600-4ec2-af96-c5cc3725a233",
      "requestId": 38,
      "purpose": "Robotics workshop",
      "revisionNo": 2,
      "status": "Failed",
      "model": "stub",
      "startedAt": "2026-09-29T06:15:07.589889Z",
      "completedAt": "2026-09-29T06:15:09.803796Z",
      "durationMs": 41,
      "failureReason": "Validation failed: V05: Start: Opens at 14:00 on Fridays; V02: No room was proposed: Room search refused the request: 400: Opens at 14:00 on Fridays; Start: Opens at 14:00 on Fridays; V03: No room to …",
      "stepCount": 5,
      "toolCallCount": 8,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T06:15:07.583199Z"
    },
    {
      "id": "b471ef61-ac1d-4b97-9e7d-bd675df77646",
      "requestId": 38,
      "purpose": "Robotics workshop",
      "revisionNo": 1,
      "status": "Failed",
      "model": "stub",
      "startedAt": "2026-09-29T06:15:04.894103Z",
      "completedAt": "2026-09-29T06:15:07.574364Z",
      "durationMs": 1917,
      "failureReason": "Final re-check failed: V02: Room A301 is no longer free for the requested window; V08: Equipment could not be re-checked: HTTP 400: Opens at 14:00 on Fridays; Start: Opens at 14:00 on Fridays",
      "stepCount": 6,
      "toolCallCount": 15,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T06:15:04.887542Z"
    },
    {
      "id": "96706692-a0be-43ac-b544-183a56bb4c1f",
      "requestId": 37,
      "purpose": "Robotics workshop",
      "revisionNo": 2,
      "status": "Rejected",
      "model": "stub",
      "startedAt": "2026-09-29T06:14:59.524112Z",
      "completedAt": "2026-09-29T06:15:04.849794Z",
      "durationMs": 4295,
      "failureReason": null,
      "stepCount": 10,
      "toolCallCount": 21,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T06:14:59.51694Z"
    },
    {
      "id": "993df35c-921c-44cd-a288-2dc2635d1691",
      "requestId": 36,
      "purpose": "Robotics workshop",
      "revisionNo": 1,
      "status": "Completed",
      "model": "stub",
      "startedAt": "2026-09-29T06:14:55.499186Z",
      "completedAt": "2026-09-29T06:14:59.435169Z",
      "durationMs": 3395,
      "failureReason": null,
      "stepCount": 6,
      "toolCallCount": 15,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T06:14:55.425634Z"
    },
    {
      "id": "11602dec-576f-4f94-8127-b6b910dc0c48",
      "requestId": 35,
      "purpose": "3.4 approve",
      "revisionNo": 1,
      "status": "Completed",
      "model": "stub",
      "startedAt": "2026-09-29T05:53:07.417691Z",
      "completedAt": "2026-09-29T05:53:41.153242Z",
      "durationMs": 33162,
      "failureReason": null,
      "stepCount": 6,
      "toolCallCount": 15,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T05:53:07.287339Z"
    },
    {
      "id": "1069235b-1176-49b6-8eb4-08e4a0739d67",
      "requestId": 34,
      "purpose": "Robotics agent down",
      "revisionNo": 2,
      "status": "Failed",
      "model": "stub",
      "startedAt": "2026-09-29T05:05:11.794566Z",
      "completedAt": "2026-09-29T05:05:13.471387Z",
      "durationMs": 47,
      "failureReason": "No room available: Every free room with ac, projector, sound_system seats more than 75 (3 × 25 attendees)",
      "stepCount": 4,
      "toolCallCount": 6,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T05:05:11.7698Z"
    },
    {
      "id": "8dc722eb-91c5-4bc7-b449-915a09c5edd1",
      "requestId": 34,
      "purpose": "Robotics agent down",
      "revisionNo": 1,
      "status": "Failed",
      "model": null,
      "startedAt": null,
      "completedAt": "2026-09-29T05:04:16.459445Z",
      "durationMs": null,
      "failureReason": "Agent service unreachable (last error: network error)",
      "stepCount": 0,
      "toolCallCount": 0,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T05:02:13.893761Z"
    },
    {
      "id": "e984d669-078e-46d3-ab55-c087571931c7",
      "requestId": 33,
      "purpose": "Robotics workshop 3",
      "revisionNo": 1,
      "status": "Cancelled",
      "model": "stub",
      "startedAt": "2026-09-29T04:50:31.253949Z",
      "completedAt": "2026-09-29T05:01:34.585802Z",
      "durationMs": 336,
      "failureReason": null,
      "stepCount": 5,
      "toolCallCount": 12,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-29T04:50:31.122285Z"
    },
    {
      "id": "1242ceee-9f8b-4276-b637-d9c3919168eb",
      "requestId": 32,
      "purpose": "3.3 live check: agent down",
      "revisionNo": 2,
      "status": "Cancelled",
      "model": "stub",
      "startedAt": "2026-09-28T17:08:39.95545Z",
      "completedAt": "2026-09-28T17:08:41.247955Z",
      "durationMs": 628,
      "failureReason": null,
      "stepCount": 4,
      "toolCallCount": 10,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-28T17:08:39.943581Z"
    },
    {
      "id": "eb20bf5e-e345-4899-b204-d189b153990a",
      "requestId": 32,
      "purpose": "3.3 live check: agent down",
      "revisionNo": 1,
      "status": "Failed",
      "model": null,
      "startedAt": null,
      "completedAt": "2026-09-28T17:08:34.571095Z",
      "durationMs": null,
      "failureReason": "Agent service unreachable (last error: network error)",
      "stepCount": 0,
      "toolCallCount": 0,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-28T17:06:32.416749Z"
    },
    {
      "id": "a8aa4d38-e68c-402c-b211-34480804c3b8",
      "requestId": 31,
      "purpose": "3.3 fixture capture: guest lecture",
      "revisionNo": 1,
      "status": "Cancelled",
      "model": "stub",
      "startedAt": "2026-09-28T17:00:22.183794Z",
      "completedAt": "2026-09-28T17:00:45.642002Z",
      "durationMs": 371,
      "failureReason": null,
      "stepCount": 5,
      "toolCallCount": 12,
      "totalTokens": null,
      "anyFallback": false,
      "createdAt": "2026-09-28T17:00:22.136442Z"
    }
  ],
  "page": 1,
  "pageSize": 20,
  "total": 20
}

/** GET /api/agent-runs/{id} of a Failed run. */
export const FAILED_RUN_DETAIL: AgentRunDetailDto = {
  "id": "8153a27b-08be-40a8-9f6d-525fb794dac3",
  "requestId": 41,
  "revisionNo": 1,
  "status": "Failed",
  "model": "stub",
  "nodes": [
    "supervisor",
    "venue_matching",
    "supervisor",
    "equipment_allocation",
    "supervisor",
    "policy_cost",
    "supervisor",
    "validate",
    "human_gate",
    "finalize"
  ],
  "officerSummary": "E201 fits 30 attendees (40 seats) with projector. Equipment: 1 × MIC-WIRELESS. Total LKR 3,500.00 (budget LKR 5,000.00): within budget.",
  "failureReason": "Can be booked at most 30 days ahead (as of submission)",
  "createdAt": "2026-09-29T06:18:00.906658Z",
  "startedAt": "2026-09-29T06:18:00.921757Z",
  "completedAt": "2026-09-29T06:18:04.66241Z",
  "durationMs": 2824,
  "proposal": {
    "chosen": {
      "roomId": 14,
      "code": "E201",
      "name": "Computer Lab E201",
      "capacity": 40,
      "building": "Engineering Building",
      "features": [
        "computers",
        "projector",
        "whiteboard"
      ],
      "reason": "40 seats for 30 attendees; has projector; Engineering Building"
    },
    "alternatives": [
      {
        "roomId": 1,
        "code": "A301",
        "name": "Computer Lab A301",
        "capacity": 48,
        "building": "Main Building",
        "features": [
          "ac",
          "computers",
          "projector",
          "whiteboard"
        ],
        "reason": "48 seats for 30 attendees; has projector; Main Building"
      },
      {
        "roomId": 8,
        "code": "N201",
        "name": "Computer Lab N201",
        "capacity": 60,
        "building": "New Building",
        "features": [
          "ac",
          "computers",
          "projector",
          "smart_board"
        ],
        "reason": "60 seats for 30 attendees; has projector; New Building"
      }
    ],
    "venueUnmet": null,
    "equipmentLines": [
      {
        "typeCode": "MIC-WIRELESS",
        "qty": 1,
        "source": "portable"
      }
    ],
    "substitutions": [],
    "equipmentUnmet": [],
    "policyFlags": [
      "Within budget: LKR 3,500.00 vs LKR 5,000.00",
      "Duration 2 h (at most 8 h)"
    ]
  },
  "steps": [
    {
      "sequence": 1,
      "agentName": "supervisor",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 8,
      "input": {
        "revision": 1,
        "request_id": 41,
        "replan_reason": null
      },
      "output": {
        "steps": [
          {
            "task": "Find up to 3 FREE rooms that fit the attendees and have every required feature; rank them with a one-line reason each. Skip excluded rooms.",
            "agent": "venue_matching"
          },
          {
            "task": "For the chosen room, drop lines its features cover (room_builtin), check availability of the rest, and propose a substitute when a line is short.",
            "agent": "equipment_allocation"
          },
          {
            "task": "Price the chosen room and priced lines with calculate_quote, list the policy facts, and write a short officer summary.",
            "agent": "policy_cost"
          }
        ],
        "equipment": [
          {
            "quantity": 1,
            "type_code": "MIC-WIRELESS"
          }
        ],
        "planner_fallback": false,
        "soft_preferences": [],
        "required_features": [
          "projector"
        ]
      },
      "toolCalls": [
        {
          "toolName": "get_policy",
          "args": {},
          "resultSummary": {
            "keys": [
              "checkout_window_minutes",
              "free_cancellation_hours",
              "max_advance_days_lecturer",
              "max_advance_days_student",
              "max_capacity_ratio",
              "max_duration_hours",
              "max_open_requests",
              "min_lead_time_hours",
              "opening_hours",
              "slot_granularity_minutes"
            ]
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "get_request_context",
          "args": {
            "request_id": 41
          },
          "resultSummary": {
            "notes": null,
            "status": "AgentProcessing",
            "hasClub": true,
            "attendees": 30,
            "requestId": 41,
            "requestedEnd": "2026-11-20T10:30:00Z",
            "requesterRole": "Student",
            "equipmentLines": 1,
            "requestedStart": "2026-11-20T08:30:00Z",
            "maxOpenRequests": 3,
            "openRequestCount": 1
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "list_feature_catalog",
          "args": {},
          "resultSummary": {
            "count": 6
          },
          "succeeded": true,
          "error": null,
          "durationMs": 1
        },
        {
          "toolName": "list_equipment_catalog",
          "args": {},
          "resultSummary": {
            "count": 10
          },
          "succeeded": true,
          "error": null,
          "durationMs": 1
        }
      ]
    },
    {
      "sequence": 2,
      "agentName": "venue_matching",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 5,
      "input": {
        "task": "Find up to 3 FREE rooms that fit the attendees and have every required feature; rank them with a one-line reason each. Skip excluded rooms.\nBRIEF: {\"attendees\": 30, \"end\": \"2026-11-20T10:30:00Z\", \"excluded_room_ids\": [], \"max_capacity_ratio\": 3, \"replan_reason\": null, \"required_features\": [\"projector\"], \"soft_preferences\": [], \"start\": \"2026-11-20T08:30:00Z\"}"
      },
      "output": {
        "unmet": null,
        "options": [
          {
            "code": "E201",
            "name": "Computer Lab E201",
            "reason": "40 seats for 30 attendees; has projector; Engineering Building",
            "room_id": 14,
            "building": "Engineering Building",
            "capacity": 40,
            "features": [
              "computers",
              "projector",
              "whiteboard"
            ]
          },
          {
            "code": "A301",
            "name": "Computer Lab A301",
            "reason": "48 seats for 30 attendees; has projector; Main Building",
            "room_id": 1,
            "building": "Main Building",
            "capacity": 48,
            "features": [
              "ac",
              "computers",
              "projector",
              "whiteboard"
            ]
          },
          {
            "code": "N201",
            "name": "Computer Lab N201",
            "reason": "60 seats for 30 attendees; has projector; New Building",
            "room_id": 8,
            "building": "New Building",
            "capacity": 60,
            "features": [
              "ac",
              "computers",
              "projector",
              "smart_board"
            ]
          }
        ]
      },
      "toolCalls": [
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-20T10:30:00Z",
            "start": "2026-11-20T08:30:00Z",
            "features": [
              "projector"
            ],
            "page_size": 100,
            "building_id": null,
            "max_capacity": null,
            "min_capacity": 30
          },
          "resultSummary": {
            "rooms": [
              "14:E201",
              "1:A301",
              "8:N201",
              "4:A102",
              "13:E101",
              "10:N102",
              "3:A101",
              "9:N101",
              "15:EB-AUD",
              "7:MB-AUD"
            ],
            "total": 10
          },
          "succeeded": true,
          "error": null,
          "durationMs": 5
        }
      ]
    },
    {
      "sequence": 3,
      "agentName": "equipment_allocation",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 3,
      "input": {
        "task": "For the chosen room, drop lines its features cover (room_builtin), check availability of the rest, and propose a substitute when a line is short.\nBRIEF: {\"end\": \"2026-11-20T10:30:00Z\", \"lines\": [{\"code\": \"MIC-WIRELESS\", \"quantity\": 1}], \"room_features\": [\"computers\", \"projector\", \"whiteboard\"], \"room_id\": 14, \"start\": \"2026-11-20T08:30:00Z\"}"
      },
      "output": {
        "lines": [
          {
            "qty": 1,
            "source": "portable",
            "type_code": "MIC-WIRELESS"
          }
        ],
        "unmet": [],
        "substitutions": []
      },
      "toolCalls": [
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-20T10:30:00Z",
            "codes": [
              "MIC-WIRELESS"
            ],
            "start": "2026-11-20T08:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        }
      ]
    },
    {
      "sequence": 4,
      "agentName": "policy_cost",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 3,
      "input": {
        "task": "Price the chosen room and priced lines with calculate_quote, list the policy facts, and write a short officer summary.\nBRIEF: {\"attendees\": 30, \"budget_lkr\": \"5000.00\", \"builtin\": [], \"duration_hours\": \"2.00\", \"end\": \"2026-11-20T10:30:00Z\", \"equipment_unmet\": [], \"policy\": {\"max_advance_days_lecturer\": 90, \"max_advance_days_student\": 60, \"max_capacity_ratio\": 3, \"max_duration_hours\": 8, \"max_open_requests\": 3, \"min_lead_time_hours\": 48}, \"priced_lines\": [{\"code\": \"MIC-WIRELESS\", \"quantity\": 1}], \"requester_role\": \"Student\", \"required_features\": [\"projector\"], \"room_capacity\": 40, \"room_code\": \"E201\", \"room_id\": 14, \"start\": \"2026-11-20T08:30:00Z\", \"substitutions\": [], \"venue_unmet\": null}"
      },
      "output": {
        "quote": {
          "lines": [
            {
              "qty": "2.00",
              "kind": "Room",
              "line_total": "3000.00",
              "unit_price": "1500.00",
              "description": "Computer lab E201, 2 h @ LKR 1,500"
            },
            {
              "qty": "1.00",
              "kind": "Equipment",
              "line_total": "500.00",
              "unit_price": "500.00",
              "description": "Wireless microphone x1 @ LKR 500"
            }
          ],
          "total": "3500.00",
          "exempt": false,
          "currency": "LKR",
          "discount": "0.00",
          "subtotal": "3500.00",
          "discount_reason": null
        },
        "unmet": null,
        "policy_flags": [
          "Within budget: LKR 3,500.00 vs LKR 5,000.00",
          "Duration 2 h (at most 8 h)"
        ],
        "officer_summary": "E201 fits 30 attendees (40 seats) with projector. Equipment: 1 × MIC-WIRELESS. Total LKR 3,500.00 (budget LKR 5,000.00): within budget."
      },
      "toolCalls": [
        {
          "toolName": "calculate_quote",
          "args": {
            "end": "2026-11-20T10:30:00Z",
            "start": "2026-11-20T08:30:00Z",
            "room_id": 14,
            "equipment": [
              {
                "code": "MIC-WIRELESS",
                "quantity": 1
              }
            ],
            "requester_role": "Student"
          },
          "resultSummary": {
            "lines": 2,
            "total": "3500.00",
            "exempt": false
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        }
      ]
    },
    {
      "sequence": 5,
      "agentName": "validate",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 11,
      "input": {
        "attempt": 1,
        "room_id": 14
      },
      "output": {
        "failed": [],
        "outcome": "pass"
      },
      "toolCalls": [
        {
          "toolName": "get_room_details",
          "args": {
            "room_id": 14
          },
          "resultSummary": {
            "id": 14,
            "code": "E201",
            "capacity": 40,
            "features": [
              "computers",
              "projector",
              "whiteboard"
            ],
            "isActive": true
          },
          "succeeded": true,
          "error": null,
          "durationMs": 1
        },
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-20T10:30:00Z",
            "start": "2026-11-20T08:30:00Z",
            "features": [],
            "page_size": 100,
            "building_id": 3,
            "max_capacity": 40,
            "min_capacity": 40
          },
          "resultSummary": {
            "rooms": [
              "14:E201"
            ],
            "total": 1
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-20T10:30:00Z",
            "codes": [
              "MIC-WIRELESS"
            ],
            "start": "2026-11-20T08:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "calculate_quote",
          "args": {
            "end": "2026-11-20T10:30:00Z",
            "start": "2026-11-20T08:30:00Z",
            "room_id": 14,
            "equipment": [
              {
                "code": "MIC-WIRELESS",
                "quantity": 1
              }
            ],
            "requester_role": "Student"
          },
          "resultSummary": {
            "lines": 2,
            "total": "3500.00",
            "exempt": false
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "get_request_context",
          "args": {
            "request_id": 41
          },
          "resultSummary": {
            "notes": null,
            "status": "AgentProcessing",
            "hasClub": true,
            "attendees": 30,
            "requestId": 41,
            "requestedEnd": "2026-11-20T10:30:00Z",
            "requesterRole": "Student",
            "equipmentLines": 1,
            "requestedStart": "2026-11-20T08:30:00Z",
            "maxOpenRequests": 3,
            "openRequestCount": 1
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        }
      ]
    },
    {
      "sequence": 6,
      "agentName": "finalize",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 10,
      "input": {
        "room_id": 14
      },
      "output": {
        "V02": {
          "passed": true,
          "message": "Room E201 exists and is still free for the window"
        },
        "V08": {
          "passed": true,
          "message": "1 × MIC-WIRELESS available (7)"
        }
      },
      "toolCalls": [
        {
          "toolName": "get_room_details",
          "args": {
            "room_id": 14
          },
          "resultSummary": {
            "id": 14,
            "code": "E201",
            "capacity": 40,
            "features": [
              "computers",
              "projector",
              "whiteboard"
            ],
            "isActive": true
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        },
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-20T10:30:00Z",
            "start": "2026-11-20T08:30:00Z",
            "features": [],
            "page_size": 100,
            "building_id": 3,
            "max_capacity": 40,
            "min_capacity": 40
          },
          "resultSummary": {
            "rooms": [
              "14:E201"
            ],
            "total": 1
          },
          "succeeded": true,
          "error": null,
          "durationMs": 4
        },
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-20T10:30:00Z",
            "codes": [
              "MIC-WIRELESS"
            ],
            "start": "2026-11-20T08:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        }
      ]
    }
  ],
  "validation": [
    {
      "attempt": 1,
      "rules": [
        {
          "rule": "V01",
          "passed": true,
          "message": "4 outputs match their schemas (extra fields forbidden)"
        },
        {
          "rule": "V02",
          "passed": true,
          "message": "Room E201 exists and is still free for the window"
        },
        {
          "rule": "V03",
          "passed": true,
          "message": "40 seats for 30 attendees (at most 90)"
        },
        {
          "rule": "V04",
          "passed": true,
          "message": "Room E201 has projector"
        },
        {
          "rule": "V05",
          "passed": true,
          "message": "Fri 14:00–16:00 is within 08:00–20:00, 2 h ≤ 8 h, on 30-minute boundaries"
        },
        {
          "rule": "V06",
          "passed": true,
          "message": "Starts ≥ 48 h from now and within 60 days (Student)"
        },
        {
          "rule": "V07",
          "passed": true,
          "message": "No blackout or booking overlaps room E201; public holidays are not checked (not implemented)"
        },
        {
          "rule": "V08",
          "passed": true,
          "message": "1 × MIC-WIRELESS available (7)"
        },
        {
          "rule": "V09",
          "passed": true,
          "message": "Total LKR 3,500.00 equals the .NET recomputation"
        },
        {
          "rule": "V10",
          "passed": true,
          "message": "LKR 3,500.00 ≤ budget LKR 5,000.00"
        },
        {
          "rule": "V11",
          "passed": true,
          "message": "active club, registered rep; 1 other open requests < 3"
        },
        {
          "rule": "V12",
          "passed": true,
          "message": "3 room ids and 1 equipment codes came from tool results"
        }
      ]
    }
  ],
  "decisions": [
    {
      "decision": "Approve",
      "officerName": "Mr. Perera",
      "comment": null,
      "decidedAt": "2026-09-29T06:18:04.114195Z"
    }
  ],
  "policySnapshot": {
    "opening_hours": {
      "fri": {
        "open": "08:00",
        "close": "20:00"
      },
      "mon": {
        "open": "08:00",
        "close": "20:00"
      },
      "sat": {
        "open": "08:00",
        "close": "16:00"
      },
      "sun": null,
      "thu": {
        "open": "08:00",
        "close": "20:00"
      },
      "tue": {
        "open": "08:00",
        "close": "20:00"
      },
      "wed": {
        "open": "08:00",
        "close": "20:00"
      }
    },
    "max_open_requests": 3,
    "max_capacity_ratio": 3,
    "max_duration_hours": 8,
    "min_lead_time_hours": 48,
    "checkout_window_minutes": 30,
    "free_cancellation_hours": 24,
    "max_advance_days_student": 60,
    "slot_granularity_minutes": 30,
    "max_advance_days_lecturer": 90
  },
  "policyChangedKeys": []
}
