using CampusSpace.Api.Data;
using CampusSpace.Api.Models;
using Microsoft.EntityFrameworkCore;

namespace CampusSpace.Api.Agents;

public sealed class AgentRunStarter(
    AppDbContext db, IAgentClient agent, TimeProvider clock, ILogger<AgentRunStarter> logger) : IAgentRunStarter
{
    public async Task<AgentRun> AddRunAsync(BookingRequest request, CancellationToken ct = default)
    {
        var last = request.Id == 0
            ? 0
            : await db.AgentRuns.Where(r => r.RequestId == request.Id).MaxAsync(r => (int?)r.RevisionNo, ct) ?? 0;
        var run = new AgentRun
        {
            // The thread_id: generated by .NET, never taken from a client.
            Id = Guid.NewGuid(),
            Request = request,
            RevisionNo = last + 1,
            Status = AgentRunStatuses.Queued,
        };
        db.AgentRuns.Add(run);
        return run;
    }

    public async Task<AgentCallResult<AgentWorkflowAccepted>> TryStartAsync(
        Guid runId, long requestId, TimeSpan? timeout = null, CancellationToken ct = default)
    {
        AgentCallResult<AgentWorkflowAccepted> result;
        using (var limit = CancellationTokenSource.CreateLinkedTokenSource(ct))
        {
            if (timeout is { } t)
                limit.CancelAfter(t);
            try
            {
                result = await agent.StartAsync(runId, requestId, limit.Token);
            }
            catch (OperationCanceledException) when (!ct.IsCancellationRequested)
            {
                result = AgentCallResult<AgentWorkflowAccepted>.Unavailable("timeout");
            }
        }

        if (result.Outcome is AgentCallOutcome.Ok or AgentCallOutcome.AlreadyExists)
            await MarkStartedAsync(runId, requestId, ct);
        else
            logger.LogWarning("Agent run {RunId} was not started ({Outcome}: {Detail}); it stays Queued for the poller",
                runId, result.Outcome, result.Detail);
        return result;
    }

    private async Task MarkStartedAsync(Guid runId, long requestId, CancellationToken ct)
    {
        await using var transaction = await db.Database.BeginTransactionAsync(ct);
        await RowLocks.RequestAsync(db, requestId, ct);
        var run = await RowLocks.AgentRunAsync(db, runId, ct);
        // Someone else (the poller, or the watchdog) may have moved it already: then there is nothing to do.
        if (run is not { Status: AgentRunStatuses.Queued })
            return;
        run.Status = AgentRunStatuses.Running;
        run.StartedAt = clock.GetUtcNow().UtcDateTime;
        await db.SaveChangesAsync(ct);
        await transaction.CommitAsync(ct);
    }
}
