"""Workflow endpoints (plan §10.12). Every route requires X-Service-Key; only .NET calls them.

thread_id is AgentRuns.Id, generated by .NET (never by a client): it is an authorisation
boundary (Lab 06 Exercise 6.1). The graph fetches everything else through the tools, so the body
carries ids only.
"""

from uuid import UUID

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Request, status

from app.runner import Conflict, WorkflowRunner
from app.schemas import ResumeRequest, StartWorkflowRequest, WorkflowAccepted, WorkflowView
from app.security import require_service_key

router = APIRouter(tags=["workflows"], dependencies=[Depends(require_service_key)])


def _runner(request: Request) -> WorkflowRunner:
    return request.app.state.runner


@router.post("/workflows", status_code=status.HTTP_202_ACCEPTED)
def start_workflow(
    body: StartWorkflowRequest, background: BackgroundTasks, request: Request
) -> WorkflowAccepted:
    """Start a run for a booking request; poll GET /workflows/{thread_id}."""
    runner = _runner(request)
    thread_id = str(body.thread_id)
    try:
        runner.claim_start(thread_id)
    except Conflict as exc:
        raise HTTPException(status.HTTP_409_CONFLICT, str(exc)) from exc
    background.add_task(runner.run_start, thread_id, body.request_id)
    return WorkflowAccepted(thread_id=thread_id, status="running")


@router.get("/workflows/{thread_id}")
def get_workflow(thread_id: UUID, request: Request) -> WorkflowView:
    view = _runner(request).view(str(thread_id))
    if view is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Unknown thread_id")
    return view


@router.post("/workflows/{thread_id}/resume", status_code=status.HTTP_202_ACCEPTED)
def resume_workflow(
    thread_id: UUID, body: ResumeRequest, background: BackgroundTasks, request: Request
) -> WorkflowAccepted:
    """The officer's decision (approve | reject | revise | cancel), sent by .NET after its role
    check."""
    runner = _runner(request)
    key = str(thread_id)
    try:
        runner.claim_resume(key)
    except KeyError as exc:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Unknown thread_id") from exc
    except Conflict as exc:
        raise HTTPException(status.HTTP_409_CONFLICT, str(exc)) from exc
    background.add_task(runner.run_resume, key, body.decision, body.notes)
    return WorkflowAccepted(thread_id=key, status="running")
