// Real API responses captured on 2026-09-29 from the Development API with stub agents (Task 3.5).
// Generated by /tmp/checklist-3.5/make_fixtures.py from the capture scripts' output; do not edit by hand.
import type {
  AgentRunDetailDto,
  AgentRunSummaryDto,
  ApprovalQueueItemDto,
  BookingRequestDetailDto,
  PagedResult,
  QuotationDto,
} from '../../api/types'

/** A Problem Details body as the API sends it (the message is in title). */
export interface ProblemBody {
  type: string
  title: string
  status: number
  traceId: string
}

/** Kavindi's demo request waiting for approval (A301, LKR 5,500). */
export const PENDING_DETAIL: BookingRequestDetailDto = {
  "id": 42,
  "purpose": "Robotics Club Arduino workshop",
  "status": "PendingApproval",
  "attendees": 45,
  "requestedStart": "2026-11-19T08:30:00Z",
  "requestedEnd": "2026-11-19T11:30:00Z",
  "budgetLkr": 8000.0,
  "notes": "prefer near the main building",
  "requester": {
    "id": 1,
    "name": "Kavindi Perera",
    "email": "kavindi@campusspace.local",
    "role": "Student"
  },
  "club": {
    "id": 1,
    "name": "Robotics Club"
  },
  "requiredFeatures": [
    {
      "code": "computers",
      "name": "Computers"
    },
    {
      "code": "projector",
      "name": "Projector"
    }
  ],
  "equipment": [
    {
      "typeId": 1,
      "typeCode": "MIC-WIRELESS",
      "typeName": "Wireless microphone",
      "quantity": 2
    },
    {
      "typeId": 4,
      "typeCode": "PROJ-PORTABLE",
      "typeName": "Portable projector",
      "quantity": 1
    }
  ],
  "history": [
    {
      "fromStatus": null,
      "toStatus": "Submitted",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:35:49.682726Z"
    },
    {
      "fromStatus": "Submitted",
      "toStatus": "AgentProcessing",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:35:49.70113Z"
    },
    {
      "fromStatus": "AgentProcessing",
      "toStatus": "PendingApproval",
      "changedById": null,
      "changedByName": null,
      "reason": null,
      "changedAt": "2026-09-29T06:35:52.308442Z"
    }
  ],
  "latestProposal": {
    "runId": "8f5129c0-3a99-40a0-831a-0d7791c7ebe8",
    "revisionNo": 1,
    "roomId": 1,
    "roomCode": "A301",
    "roomName": "Computer Lab A301",
    "quoteId": 13,
    "total": 5500.0,
    "exempt": false,
    "quoteStatus": "Draft"
  },
  "cancelledAt": null,
  "isLateCancellation": false,
  "cancelledByOfficer": false,
  "createdAt": "2026-09-29T06:35:49.710851Z",
  "updatedAt": "2026-09-29T06:35:52.308445Z"
}

/** The same request after Approve. */
export const APPROVED_DETAIL: BookingRequestDetailDto = {
  "id": 42,
  "purpose": "Robotics Club Arduino workshop",
  "status": "Approved",
  "attendees": 45,
  "requestedStart": "2026-11-19T08:30:00Z",
  "requestedEnd": "2026-11-19T11:30:00Z",
  "budgetLkr": 8000.0,
  "notes": "prefer near the main building",
  "requester": {
    "id": 1,
    "name": "Kavindi Perera",
    "email": "kavindi@campusspace.local",
    "role": "Student"
  },
  "club": {
    "id": 1,
    "name": "Robotics Club"
  },
  "requiredFeatures": [
    {
      "code": "computers",
      "name": "Computers"
    },
    {
      "code": "projector",
      "name": "Projector"
    }
  ],
  "equipment": [
    {
      "typeId": 1,
      "typeCode": "MIC-WIRELESS",
      "typeName": "Wireless microphone",
      "quantity": 2
    },
    {
      "typeId": 4,
      "typeCode": "PROJ-PORTABLE",
      "typeName": "Portable projector",
      "quantity": 1
    }
  ],
  "history": [
    {
      "fromStatus": null,
      "toStatus": "Submitted",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:35:49.682726Z"
    },
    {
      "fromStatus": "Submitted",
      "toStatus": "AgentProcessing",
      "changedById": 1,
      "changedByName": "Kavindi Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:35:49.70113Z"
    },
    {
      "fromStatus": "AgentProcessing",
      "toStatus": "PendingApproval",
      "changedById": null,
      "changedByName": null,
      "reason": null,
      "changedAt": "2026-09-29T06:35:52.308442Z"
    },
    {
      "fromStatus": "PendingApproval",
      "toStatus": "Approved",
      "changedById": 4,
      "changedByName": "Mr. Perera",
      "reason": null,
      "changedAt": "2026-09-29T06:35:53.656418Z"
    }
  ],
  "latestProposal": {
    "runId": "8f5129c0-3a99-40a0-831a-0d7791c7ebe8",
    "revisionNo": 1,
    "roomId": 1,
    "roomCode": "A301",
    "roomName": "Computer Lab A301",
    "quoteId": 13,
    "total": 5500.0,
    "exempt": false,
    "quoteStatus": "Issued"
  },
  "cancelledAt": null,
  "isLateCancellation": false,
  "cancelledByOfficer": false,
  "createdAt": "2026-09-29T06:35:49.710851Z",
  "updatedAt": "2026-09-29T06:35:53.657477Z"
}

/** Its Draft quotation. */
export const DRAFT_QUOTE: QuotationDto = {
  "id": 13,
  "requestId": 42,
  "status": "Draft",
  "lines": [
    {
      "kind": "Room",
      "description": "Computer lab A301, 3 h @ LKR 1,500",
      "qty": 3.0,
      "unitPrice": 1500.0,
      "lineTotal": 4500.0
    },
    {
      "kind": "Equipment",
      "description": "Wireless microphone x2 @ LKR 500",
      "qty": 2.0,
      "unitPrice": 500.0,
      "lineTotal": 1000.0
    }
  ],
  "subtotal": 5500.0,
  "discount": 0.0,
  "discountReason": null,
  "exempt": false,
  "total": 5500.0,
  "currency": "LKR"
}

/** The approval queue while it was pending. */
export const QUEUE_PAGE: PagedResult<ApprovalQueueItemDto> = {
  "items": [
    {
      "requestId": 39,
      "purpose": "Robotics workshop",
      "requesterName": "Tharindu Wickramasinghe",
      "requesterRole": "Student",
      "clubName": "IEEE Student Branch",
      "start": "2026-11-17T08:30:00Z",
      "end": "2026-11-17T11:30:00Z",
      "attendees": 45,
      "proposedRoomCode": "N201",
      "draftTotal": 5500.0,
      "exempt": false,
      "revisionNo": 2,
      "pendingSince": "2026-09-29T06:15:12.809977Z"
    },
    {
      "requestId": 40,
      "purpose": "Robotics workshop",
      "requesterName": "Tharindu Wickramasinghe",
      "requesterRole": "Student",
      "clubName": "IEEE Student Branch",
      "start": "2026-11-16T08:30:00Z",
      "end": "2026-11-16T10:30:00Z",
      "attendees": 45,
      "proposedRoomCode": "A301",
      "draftTotal": 4000.0,
      "exempt": false,
      "revisionNo": 2,
      "pendingSince": "2026-09-29T06:17:18.743341Z"
    },
    {
      "requestId": 42,
      "purpose": "Robotics Club Arduino workshop",
      "requesterName": "Kavindi Perera",
      "requesterRole": "Student",
      "clubName": "Robotics Club",
      "start": "2026-11-19T08:30:00Z",
      "end": "2026-11-19T11:30:00Z",
      "attendees": 45,
      "proposedRoomCode": "A301",
      "draftTotal": 5500.0,
      "exempt": false,
      "revisionNo": 1,
      "pendingSince": "2026-09-29T06:35:52.308442Z"
    }
  ],
  "page": 1,
  "pageSize": 20,
  "total": 3
}

/** Its agent runs. */
export const PENDING_RUNS: AgentRunSummaryDto[] = [
  {
    "id": "8f5129c0-3a99-40a0-831a-0d7791c7ebe8",
    "revisionNo": 1,
    "status": "AwaitingApproval",
    "failureReason": null,
    "startedAt": "2026-09-29T06:35:49.771626Z",
    "completedAt": null,
    "durationMs": 2522,
    "model": "stub",
    "createdAt": "2026-09-29T06:35:49.710851Z"
  }
]

/** Its run: proposal, trace, 12 green rules. */
export const PENDING_RUN_DETAIL: AgentRunDetailDto = {
  "id": "8f5129c0-3a99-40a0-831a-0d7791c7ebe8",
  "requestId": 42,
  "revisionNo": 1,
  "status": "AwaitingApproval",
  "model": "stub",
  "nodes": [
    "supervisor",
    "venue_matching",
    "supervisor",
    "equipment_allocation",
    "supervisor",
    "policy_cost",
    "supervisor",
    "validate",
    "human_gate"
  ],
  "officerSummary": "A301 fits 45 attendees (48 seats) with computers, projector. Equipment: 2 × MIC-WIRELESS; PROJ-PORTABLE provided by the room. Total LKR 5,500.00 (budget LKR 8,000.00): within budget.",
  "failureReason": null,
  "createdAt": "2026-09-29T06:35:49.710851Z",
  "startedAt": "2026-09-29T06:35:49.771626Z",
  "completedAt": null,
  "durationMs": 2522,
  "proposal": {
    "chosen": {
      "roomId": 1,
      "code": "A301",
      "name": "Computer Lab A301",
      "capacity": 48,
      "building": "Main Building",
      "features": [
        "ac",
        "computers",
        "projector",
        "whiteboard"
      ],
      "reason": "48 seats for 45 attendees; has computers, projector; Main Building"
    },
    "alternatives": [
      {
        "roomId": 8,
        "code": "N201",
        "name": "Computer Lab N201",
        "capacity": 60,
        "building": "New Building",
        "features": [
          "ac",
          "computers",
          "projector",
          "smart_board"
        ],
        "reason": "60 seats for 45 attendees; has computers, projector; New Building"
      }
    ],
    "venueUnmet": null,
    "equipmentLines": [
      {
        "typeCode": "MIC-WIRELESS",
        "qty": 2,
        "source": "portable"
      },
      {
        "typeCode": "PROJ-PORTABLE",
        "qty": 0,
        "source": "room_builtin"
      }
    ],
    "substitutions": [],
    "equipmentUnmet": [],
    "policyFlags": [
      "Within budget: LKR 5,500.00 vs LKR 8,000.00",
      "Duration 3 h (at most 8 h)",
      "PROJ-PORTABLE provided by room A301 (not priced)"
    ]
  },
  "steps": [
    {
      "sequence": 1,
      "agentName": "supervisor",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 49,
      "input": {
        "revision": 1,
        "request_id": 42,
        "replan_reason": null
      },
      "output": {
        "steps": [
          {
            "task": "Find up to 3 FREE rooms that fit the attendees and have every required feature; rank them with a one-line reason each. Skip excluded rooms.",
            "agent": "venue_matching"
          },
          {
            "task": "For the chosen room, drop lines its features cover (room_builtin), check availability of the rest, and propose a substitute when a line is short.",
            "agent": "equipment_allocation"
          },
          {
            "task": "Price the chosen room and priced lines with calculate_quote, list the policy facts, and write a short officer summary.",
            "agent": "policy_cost"
          }
        ],
        "equipment": [
          {
            "quantity": 2,
            "type_code": "MIC-WIRELESS"
          },
          {
            "quantity": 1,
            "type_code": "PROJ-PORTABLE"
          }
        ],
        "planner_fallback": false,
        "soft_preferences": [],
        "required_features": [
          "computers",
          "projector"
        ]
      },
      "toolCalls": [
        {
          "toolName": "get_policy",
          "args": {},
          "resultSummary": {
            "keys": [
              "checkout_window_minutes",
              "free_cancellation_hours",
              "max_advance_days_lecturer",
              "max_advance_days_student",
              "max_capacity_ratio",
              "max_duration_hours",
              "max_open_requests",
              "min_lead_time_hours",
              "opening_hours",
              "slot_granularity_minutes"
            ]
          },
          "succeeded": true,
          "error": null,
          "durationMs": 17
        },
        {
          "toolName": "get_request_context",
          "args": {
            "request_id": 42
          },
          "resultSummary": {
            "notes": "<omitted>",
            "status": "AgentProcessing",
            "hasClub": true,
            "attendees": 45,
            "requestId": 42,
            "requestedEnd": "2026-11-19T11:30:00Z",
            "requesterRole": "Student",
            "equipmentLines": 2,
            "requestedStart": "2026-11-19T08:30:00Z",
            "maxOpenRequests": 3,
            "openRequestCount": 2
          },
          "succeeded": true,
          "error": null,
          "durationMs": 17
        },
        {
          "toolName": "list_feature_catalog",
          "args": {},
          "resultSummary": {
            "count": 6
          },
          "succeeded": true,
          "error": null,
          "durationMs": 7
        },
        {
          "toolName": "list_equipment_catalog",
          "args": {},
          "resultSummary": {
            "count": 10
          },
          "succeeded": true,
          "error": null,
          "durationMs": 5
        }
      ]
    },
    {
      "sequence": 2,
      "agentName": "venue_matching",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 35,
      "input": {
        "task": "Find up to 3 FREE rooms that fit the attendees and have every required feature; rank them with a one-line reason each. Skip excluded rooms.\nBRIEF: {\"attendees\": 45, \"end\": \"2026-11-19T11:30:00Z\", \"excluded_room_ids\": [], \"max_capacity_ratio\": 3, \"replan_reason\": null, \"required_features\": [\"computers\", \"projector\"], \"soft_preferences\": [], \"start\": \"2026-11-19T08:30:00Z\"}"
      },
      "output": {
        "unmet": null,
        "options": [
          {
            "code": "A301",
            "name": "Computer Lab A301",
            "reason": "48 seats for 45 attendees; has computers, projector; Main Building",
            "room_id": 1,
            "building": "Main Building",
            "capacity": 48,
            "features": [
              "ac",
              "computers",
              "projector",
              "whiteboard"
            ]
          },
          {
            "code": "N201",
            "name": "Computer Lab N201",
            "reason": "60 seats for 45 attendees; has computers, projector; New Building",
            "room_id": 8,
            "building": "New Building",
            "capacity": 60,
            "features": [
              "ac",
              "computers",
              "projector",
              "smart_board"
            ]
          }
        ]
      },
      "toolCalls": [
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-19T11:30:00Z",
            "start": "2026-11-19T08:30:00Z",
            "features": [
              "computers",
              "projector"
            ],
            "page_size": 100,
            "building_id": null,
            "max_capacity": null,
            "min_capacity": 45
          },
          "resultSummary": {
            "rooms": [
              "1:A301",
              "8:N201"
            ],
            "total": 2
          },
          "succeeded": true,
          "error": null,
          "durationMs": 34
        }
      ]
    },
    {
      "sequence": 3,
      "agentName": "equipment_allocation",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 14,
      "input": {
        "task": "For the chosen room, drop lines its features cover (room_builtin), check availability of the rest, and propose a substitute when a line is short.\nBRIEF: {\"end\": \"2026-11-19T11:30:00Z\", \"lines\": [{\"code\": \"MIC-WIRELESS\", \"quantity\": 2}, {\"code\": \"PROJ-PORTABLE\", \"quantity\": 1}], \"room_features\": [\"ac\", \"computers\", \"projector\", \"whiteboard\"], \"room_id\": 1, \"start\": \"2026-11-19T08:30:00Z\"}"
      },
      "output": {
        "lines": [
          {
            "qty": 2,
            "source": "portable",
            "type_code": "MIC-WIRELESS"
          },
          {
            "qty": 0,
            "source": "room_builtin",
            "type_code": "PROJ-PORTABLE"
          }
        ],
        "unmet": [],
        "substitutions": []
      },
      "toolCalls": [
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-19T11:30:00Z",
            "codes": [
              "MIC-WIRELESS",
              "PROJ-PORTABLE"
            ],
            "start": "2026-11-19T08:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7,
              "PROJ-PORTABLE": 5
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 14
        }
      ]
    },
    {
      "sequence": 4,
      "agentName": "policy_cost",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 18,
      "input": {
        "task": "Price the chosen room and priced lines with calculate_quote, list the policy facts, and write a short officer summary.\nBRIEF: {\"attendees\": 45, \"budget_lkr\": \"8000.00\", \"builtin\": [\"PROJ-PORTABLE\"], \"duration_hours\": \"3.00\", \"end\": \"2026-11-19T11:30:00Z\", \"equipment_unmet\": [], \"policy\": {\"max_advance_days_lecturer\": 90, \"max_advance_days_student\": 60, \"max_capacity_ratio\": 3, \"max_duration_hours\": 8, \"max_open_requests\": 3, \"min_lead_time_hours\": 48}, \"priced_lines\": [{\"code\": \"MIC-WIRELESS\", \"quantity\": 2}], \"requester_role\": \"Student\", \"required_features\": [\"computers\", \"projector\"], \"room_capacity\": 48, \"room_code\": \"A301\", \"room_id\": 1, \"start\": \"2026-11-19T08:30:00Z\", \"substitutions\": [], \"venue_unmet\": null}"
      },
      "output": {
        "quote": {
          "lines": [
            {
              "qty": "3.00",
              "kind": "Room",
              "line_total": "4500.00",
              "unit_price": "1500.00",
              "description": "Computer lab A301, 3 h @ LKR 1,500"
            },
            {
              "qty": "2.00",
              "kind": "Equipment",
              "line_total": "1000.00",
              "unit_price": "500.00",
              "description": "Wireless microphone x2 @ LKR 500"
            }
          ],
          "total": "5500.00",
          "exempt": false,
          "currency": "LKR",
          "discount": "0.00",
          "subtotal": "5500.00",
          "discount_reason": null
        },
        "unmet": null,
        "policy_flags": [
          "Within budget: LKR 5,500.00 vs LKR 8,000.00",
          "Duration 3 h (at most 8 h)",
          "PROJ-PORTABLE provided by room A301 (not priced)"
        ],
        "officer_summary": "A301 fits 45 attendees (48 seats) with computers, projector. Equipment: 2 × MIC-WIRELESS; PROJ-PORTABLE provided by the room. Total LKR 5,500.00 (budget LKR 8,000.00): within budget."
      },
      "toolCalls": [
        {
          "toolName": "calculate_quote",
          "args": {
            "end": "2026-11-19T11:30:00Z",
            "start": "2026-11-19T08:30:00Z",
            "room_id": 1,
            "equipment": [
              {
                "code": "MIC-WIRELESS",
                "quantity": 2
              }
            ],
            "requester_role": "Student"
          },
          "resultSummary": {
            "lines": 2,
            "total": "5500.00",
            "exempt": false
          },
          "succeeded": true,
          "error": null,
          "durationMs": 17
        }
      ]
    },
    {
      "sequence": 5,
      "agentName": "validate",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 28,
      "input": {
        "attempt": 1,
        "room_id": 1
      },
      "output": {
        "failed": [],
        "outcome": "pass"
      },
      "toolCalls": [
        {
          "toolName": "get_room_details",
          "args": {
            "room_id": 1
          },
          "resultSummary": {
            "id": 1,
            "code": "A301",
            "capacity": 48,
            "features": [
              "ac",
              "computers",
              "projector",
              "whiteboard"
            ],
            "isActive": true
          },
          "succeeded": true,
          "error": null,
          "durationMs": 6
        },
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-19T11:30:00Z",
            "start": "2026-11-19T08:30:00Z",
            "features": [],
            "page_size": 100,
            "building_id": 1,
            "max_capacity": 48,
            "min_capacity": 48
          },
          "resultSummary": {
            "rooms": [
              "1:A301"
            ],
            "total": 1
          },
          "succeeded": true,
          "error": null,
          "durationMs": 9
        },
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-19T11:30:00Z",
            "codes": [
              "MIC-WIRELESS",
              "PROJ-PORTABLE"
            ],
            "start": "2026-11-19T08:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7,
              "PROJ-PORTABLE": 5
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 4
        },
        {
          "toolName": "calculate_quote",
          "args": {
            "end": "2026-11-19T11:30:00Z",
            "start": "2026-11-19T08:30:00Z",
            "room_id": 1,
            "equipment": [
              {
                "code": "MIC-WIRELESS",
                "quantity": 2
              }
            ],
            "requester_role": "Student"
          },
          "resultSummary": {
            "lines": 2,
            "total": "5500.00",
            "exempt": false
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        },
        {
          "toolName": "get_request_context",
          "args": {
            "request_id": 42
          },
          "resultSummary": {
            "notes": "<omitted>",
            "status": "AgentProcessing",
            "hasClub": true,
            "attendees": 45,
            "requestId": 42,
            "requestedEnd": "2026-11-19T11:30:00Z",
            "requesterRole": "Student",
            "equipmentLines": 2,
            "requestedStart": "2026-11-19T08:30:00Z",
            "maxOpenRequests": 3,
            "openRequestCount": 2
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        }
      ]
    }
  ],
  "validation": [
    {
      "attempt": 1,
      "rules": [
        {
          "rule": "V01",
          "passed": true,
          "message": "4 outputs match their schemas (extra fields forbidden)"
        },
        {
          "rule": "V02",
          "passed": true,
          "message": "Room A301 exists and is still free for the window"
        },
        {
          "rule": "V03",
          "passed": true,
          "message": "48 seats for 45 attendees (at most 135)"
        },
        {
          "rule": "V04",
          "passed": true,
          "message": "Room A301 has computers, projector"
        },
        {
          "rule": "V05",
          "passed": true,
          "message": "Thu 14:00–17:00 is within 08:00–20:00, 3 h ≤ 8 h, on 30-minute boundaries"
        },
        {
          "rule": "V06",
          "passed": true,
          "message": "Starts ≥ 48 h from now and within 60 days (Student)"
        },
        {
          "rule": "V07",
          "passed": true,
          "message": "No blackout or booking overlaps room A301; public holidays are not checked (not implemented)"
        },
        {
          "rule": "V08",
          "passed": true,
          "message": "PROJ-PORTABLE provided by the room (projector); 2 × MIC-WIRELESS available (7)"
        },
        {
          "rule": "V09",
          "passed": true,
          "message": "Total LKR 5,500.00 equals the .NET recomputation"
        },
        {
          "rule": "V10",
          "passed": true,
          "message": "LKR 5,500.00 ≤ budget LKR 8,000.00"
        },
        {
          "rule": "V11",
          "passed": true,
          "message": "active club, registered rep; 2 other open requests < 3"
        },
        {
          "rule": "V12",
          "passed": true,
          "message": "2 room ids and 2 equipment codes came from tool results"
        }
      ]
    }
  ],
  "decisions": [],
  "policySnapshot": {
    "opening_hours": {
      "fri": {
        "open": "08:00",
        "close": "20:00"
      },
      "mon": {
        "open": "08:00",
        "close": "20:00"
      },
      "sat": {
        "open": "08:00",
        "close": "16:00"
      },
      "sun": null,
      "thu": {
        "open": "08:00",
        "close": "20:00"
      },
      "tue": {
        "open": "08:00",
        "close": "20:00"
      },
      "wed": {
        "open": "08:00",
        "close": "20:00"
      }
    },
    "max_open_requests": 3,
    "max_capacity_ratio": 3,
    "max_duration_hours": 8,
    "min_lead_time_hours": 48,
    "checkout_window_minutes": 30,
    "free_cancellation_hours": 24,
    "max_advance_days_student": 60,
    "slot_granularity_minutes": 30,
    "max_advance_days_lecturer": 90
  },
  "policyChangedKeys": []
}

/** A run after Request revision (revision 2, two attempts). */
export const REVISED_RUN_DETAIL: AgentRunDetailDto = {
  "id": "96706692-a0be-43ac-b544-183a56bb4c1f",
  "requestId": 37,
  "revisionNo": 2,
  "status": "AwaitingApproval",
  "model": "stub",
  "nodes": [
    "supervisor",
    "venue_matching",
    "supervisor",
    "equipment_allocation",
    "supervisor",
    "policy_cost",
    "supervisor",
    "validate",
    "human_gate",
    "supervisor",
    "venue_matching",
    "supervisor",
    "equipment_allocation",
    "supervisor",
    "policy_cost",
    "supervisor",
    "validate",
    "human_gate"
  ],
  "officerSummary": "N201 fits 45 attendees (60 seats) with computers, projector. Equipment: 2 × MIC-WIRELESS; PROJ-PORTABLE provided by the room. Total LKR 5,500.00 (budget LKR 8,000.00): within budget.",
  "failureReason": null,
  "createdAt": "2026-09-29T06:14:59.51694Z",
  "startedAt": "2026-09-29T06:14:59.524112Z",
  "completedAt": null,
  "durationMs": 4295,
  "proposal": {
    "chosen": {
      "roomId": 8,
      "code": "N201",
      "name": "Computer Lab N201",
      "capacity": 60,
      "building": "New Building",
      "features": [
        "ac",
        "computers",
        "projector",
        "smart_board"
      ],
      "reason": "60 seats for 45 attendees; has computers, projector; New Building"
    },
    "alternatives": [],
    "venueUnmet": null,
    "equipmentLines": [
      {
        "typeCode": "MIC-WIRELESS",
        "qty": 2,
        "source": "portable"
      },
      {
        "typeCode": "PROJ-PORTABLE",
        "qty": 0,
        "source": "room_builtin"
      }
    ],
    "substitutions": [],
    "equipmentUnmet": [],
    "policyFlags": [
      "Within budget: LKR 5,500.00 vs LKR 8,000.00",
      "Duration 3 h (at most 8 h)",
      "PROJ-PORTABLE provided by room N201 (not priced)"
    ]
  },
  "steps": [
    {
      "sequence": 1,
      "agentName": "supervisor",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 5,
      "input": {
        "revision": 1,
        "request_id": 37,
        "replan_reason": null
      },
      "output": {
        "steps": [
          {
            "task": "Find up to 3 FREE rooms that fit the attendees and have every required feature; rank them with a one-line reason each. Skip excluded rooms.",
            "agent": "venue_matching"
          },
          {
            "task": "For the chosen room, drop lines its features cover (room_builtin), check availability of the rest, and propose a substitute when a line is short.",
            "agent": "equipment_allocation"
          },
          {
            "task": "Price the chosen room and priced lines with calculate_quote, list the policy facts, and write a short officer summary.",
            "agent": "policy_cost"
          }
        ],
        "equipment": [
          {
            "quantity": 2,
            "type_code": "MIC-WIRELESS"
          },
          {
            "quantity": 1,
            "type_code": "PROJ-PORTABLE"
          }
        ],
        "planner_fallback": false,
        "soft_preferences": [],
        "required_features": [
          "computers",
          "projector"
        ]
      },
      "toolCalls": [
        {
          "toolName": "get_policy",
          "args": {},
          "resultSummary": {
            "keys": [
              "checkout_window_minutes",
              "free_cancellation_hours",
              "max_advance_days_lecturer",
              "max_advance_days_student",
              "max_capacity_ratio",
              "max_duration_hours",
              "max_open_requests",
              "min_lead_time_hours",
              "opening_hours",
              "slot_granularity_minutes"
            ]
          },
          "succeeded": true,
          "error": null,
          "durationMs": 1
        },
        {
          "toolName": "get_request_context",
          "args": {
            "request_id": 37
          },
          "resultSummary": {
            "notes": null,
            "status": "AgentProcessing",
            "hasClub": true,
            "attendees": 45,
            "requestId": 37,
            "requestedEnd": "2026-11-18T06:30:00Z",
            "requesterRole": "Student",
            "equipmentLines": 2,
            "requestedStart": "2026-11-18T03:30:00Z",
            "maxOpenRequests": 3,
            "openRequestCount": 2
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "list_feature_catalog",
          "args": {},
          "resultSummary": {
            "count": 6
          },
          "succeeded": true,
          "error": null,
          "durationMs": 0
        },
        {
          "toolName": "list_equipment_catalog",
          "args": {},
          "resultSummary": {
            "count": 10
          },
          "succeeded": true,
          "error": null,
          "durationMs": 0
        }
      ]
    },
    {
      "sequence": 2,
      "agentName": "venue_matching",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 3,
      "input": {
        "task": "Find up to 3 FREE rooms that fit the attendees and have every required feature; rank them with a one-line reason each. Skip excluded rooms.\nBRIEF: {\"attendees\": 45, \"end\": \"2026-11-18T06:30:00Z\", \"excluded_room_ids\": [], \"max_capacity_ratio\": 3, \"replan_reason\": null, \"required_features\": [\"computers\", \"projector\"], \"soft_preferences\": [], \"start\": \"2026-11-18T03:30:00Z\"}"
      },
      "output": {
        "unmet": null,
        "options": [
          {
            "code": "A301",
            "name": "Computer Lab A301",
            "reason": "48 seats for 45 attendees; has computers, projector; Main Building",
            "room_id": 1,
            "building": "Main Building",
            "capacity": 48,
            "features": [
              "ac",
              "computers",
              "projector",
              "whiteboard"
            ]
          },
          {
            "code": "N201",
            "name": "Computer Lab N201",
            "reason": "60 seats for 45 attendees; has computers, projector; New Building",
            "room_id": 8,
            "building": "New Building",
            "capacity": 60,
            "features": [
              "ac",
              "computers",
              "projector",
              "smart_board"
            ]
          }
        ]
      },
      "toolCalls": [
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "start": "2026-11-18T03:30:00Z",
            "features": [
              "computers",
              "projector"
            ],
            "page_size": 100,
            "building_id": null,
            "max_capacity": null,
            "min_capacity": 45
          },
          "resultSummary": {
            "rooms": [
              "1:A301",
              "8:N201"
            ],
            "total": 2
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        }
      ]
    },
    {
      "sequence": 3,
      "agentName": "equipment_allocation",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 3,
      "input": {
        "task": "For the chosen room, drop lines its features cover (room_builtin), check availability of the rest, and propose a substitute when a line is short.\nBRIEF: {\"end\": \"2026-11-18T06:30:00Z\", \"lines\": [{\"code\": \"MIC-WIRELESS\", \"quantity\": 2}, {\"code\": \"PROJ-PORTABLE\", \"quantity\": 1}], \"room_features\": [\"ac\", \"computers\", \"projector\", \"whiteboard\"], \"room_id\": 1, \"start\": \"2026-11-18T03:30:00Z\"}"
      },
      "output": {
        "lines": [
          {
            "qty": 2,
            "source": "portable",
            "type_code": "MIC-WIRELESS"
          },
          {
            "qty": 0,
            "source": "room_builtin",
            "type_code": "PROJ-PORTABLE"
          }
        ],
        "unmet": [],
        "substitutions": []
      },
      "toolCalls": [
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "codes": [
              "MIC-WIRELESS",
              "PROJ-PORTABLE"
            ],
            "start": "2026-11-18T03:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7,
              "PROJ-PORTABLE": 5
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        }
      ]
    },
    {
      "sequence": 4,
      "agentName": "policy_cost",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 3,
      "input": {
        "task": "Price the chosen room and priced lines with calculate_quote, list the policy facts, and write a short officer summary.\nBRIEF: {\"attendees\": 45, \"budget_lkr\": \"8000.00\", \"builtin\": [\"PROJ-PORTABLE\"], \"duration_hours\": \"3.00\", \"end\": \"2026-11-18T06:30:00Z\", \"equipment_unmet\": [], \"policy\": {\"max_advance_days_lecturer\": 90, \"max_advance_days_student\": 60, \"max_capacity_ratio\": 3, \"max_duration_hours\": 8, \"max_open_requests\": 3, \"min_lead_time_hours\": 48}, \"priced_lines\": [{\"code\": \"MIC-WIRELESS\", \"quantity\": 2}], \"requester_role\": \"Student\", \"required_features\": [\"computers\", \"projector\"], \"room_capacity\": 48, \"room_code\": \"A301\", \"room_id\": 1, \"start\": \"2026-11-18T03:30:00Z\", \"substitutions\": [], \"venue_unmet\": null}"
      },
      "output": {
        "quote": {
          "lines": [
            {
              "qty": "3.00",
              "kind": "Room",
              "line_total": "4500.00",
              "unit_price": "1500.00",
              "description": "Computer lab A301, 3 h @ LKR 1,500"
            },
            {
              "qty": "2.00",
              "kind": "Equipment",
              "line_total": "1000.00",
              "unit_price": "500.00",
              "description": "Wireless microphone x2 @ LKR 500"
            }
          ],
          "total": "5500.00",
          "exempt": false,
          "currency": "LKR",
          "discount": "0.00",
          "subtotal": "5500.00",
          "discount_reason": null
        },
        "unmet": null,
        "policy_flags": [
          "Within budget: LKR 5,500.00 vs LKR 8,000.00",
          "Duration 3 h (at most 8 h)",
          "PROJ-PORTABLE provided by room A301 (not priced)"
        ],
        "officer_summary": "A301 fits 45 attendees (48 seats) with computers, projector. Equipment: 2 × MIC-WIRELESS; PROJ-PORTABLE provided by the room. Total LKR 5,500.00 (budget LKR 8,000.00): within budget."
      },
      "toolCalls": [
        {
          "toolName": "calculate_quote",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "start": "2026-11-18T03:30:00Z",
            "room_id": 1,
            "equipment": [
              {
                "code": "MIC-WIRELESS",
                "quantity": 2
              }
            ],
            "requester_role": "Student"
          },
          "resultSummary": {
            "lines": 2,
            "total": "5500.00",
            "exempt": false
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        }
      ]
    },
    {
      "sequence": 5,
      "agentName": "validate",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 12,
      "input": {
        "attempt": 1,
        "room_id": 1
      },
      "output": {
        "failed": [],
        "outcome": "pass"
      },
      "toolCalls": [
        {
          "toolName": "get_room_details",
          "args": {
            "room_id": 1
          },
          "resultSummary": {
            "id": 1,
            "code": "A301",
            "capacity": 48,
            "features": [
              "ac",
              "computers",
              "projector",
              "whiteboard"
            ],
            "isActive": true
          },
          "succeeded": true,
          "error": null,
          "durationMs": 1
        },
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "start": "2026-11-18T03:30:00Z",
            "features": [],
            "page_size": 100,
            "building_id": 1,
            "max_capacity": 48,
            "min_capacity": 48
          },
          "resultSummary": {
            "rooms": [
              "1:A301"
            ],
            "total": 1
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        },
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "codes": [
              "MIC-WIRELESS",
              "PROJ-PORTABLE"
            ],
            "start": "2026-11-18T03:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7,
              "PROJ-PORTABLE": 5
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "calculate_quote",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "start": "2026-11-18T03:30:00Z",
            "room_id": 1,
            "equipment": [
              {
                "code": "MIC-WIRELESS",
                "quantity": 2
              }
            ],
            "requester_role": "Student"
          },
          "resultSummary": {
            "lines": 2,
            "total": "5500.00",
            "exempt": false
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "get_request_context",
          "args": {
            "request_id": 37
          },
          "resultSummary": {
            "notes": null,
            "status": "AgentProcessing",
            "hasClub": true,
            "attendees": 45,
            "requestId": 37,
            "requestedEnd": "2026-11-18T06:30:00Z",
            "requesterRole": "Student",
            "equipmentLines": 2,
            "requestedStart": "2026-11-18T03:30:00Z",
            "maxOpenRequests": 3,
            "openRequestCount": 2
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        }
      ]
    },
    {
      "sequence": 6,
      "agentName": "supervisor",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 1,
      "input": {
        "revision": 2,
        "request_id": 37,
        "replan_reason": "Officer revision: Use a lab in the New Building"
      },
      "output": {
        "steps": [
          {
            "task": "Find up to 3 FREE rooms that fit the attendees and have every required feature; rank them with a one-line reason each. Skip excluded rooms.",
            "agent": "venue_matching"
          },
          {
            "task": "For the chosen room, drop lines its features cover (room_builtin), check availability of the rest, and propose a substitute when a line is short.",
            "agent": "equipment_allocation"
          },
          {
            "task": "Price the chosen room and priced lines with calculate_quote, list the policy facts, and write a short officer summary.",
            "agent": "policy_cost"
          }
        ],
        "equipment": [
          {
            "quantity": 2,
            "type_code": "MIC-WIRELESS"
          },
          {
            "quantity": 1,
            "type_code": "PROJ-PORTABLE"
          }
        ],
        "planner_fallback": false,
        "soft_preferences": [],
        "required_features": [
          "computers",
          "projector"
        ]
      },
      "toolCalls": [
        {
          "toolName": "get_policy",
          "args": {},
          "resultSummary": {
            "keys": [
              "checkout_window_minutes",
              "free_cancellation_hours",
              "max_advance_days_lecturer",
              "max_advance_days_student",
              "max_capacity_ratio",
              "max_duration_hours",
              "max_open_requests",
              "min_lead_time_hours",
              "opening_hours",
              "slot_granularity_minutes"
            ]
          },
          "succeeded": true,
          "error": null,
          "durationMs": 1
        }
      ]
    },
    {
      "sequence": 7,
      "agentName": "venue_matching",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 4,
      "input": {
        "task": "Find up to 3 FREE rooms that fit the attendees and have every required feature; rank them with a one-line reason each. Skip excluded rooms.\nBRIEF: {\"attendees\": 45, \"end\": \"2026-11-18T06:30:00Z\", \"excluded_room_ids\": [1], \"max_capacity_ratio\": 3, \"replan_reason\": \"Officer revision: Use a lab in the New Building\", \"required_features\": [\"computers\", \"projector\"], \"soft_preferences\": [], \"start\": \"2026-11-18T03:30:00Z\"}"
      },
      "output": {
        "unmet": null,
        "options": [
          {
            "code": "N201",
            "name": "Computer Lab N201",
            "reason": "60 seats for 45 attendees; has computers, projector; New Building",
            "room_id": 8,
            "building": "New Building",
            "capacity": 60,
            "features": [
              "ac",
              "computers",
              "projector",
              "smart_board"
            ]
          }
        ]
      },
      "toolCalls": [
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "start": "2026-11-18T03:30:00Z",
            "features": [
              "computers",
              "projector"
            ],
            "page_size": 100,
            "building_id": null,
            "max_capacity": null,
            "min_capacity": 45
          },
          "resultSummary": {
            "rooms": [
              "1:A301",
              "8:N201"
            ],
            "total": 2
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        }
      ]
    },
    {
      "sequence": 8,
      "agentName": "equipment_allocation",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 3,
      "input": {
        "task": "For the chosen room, drop lines its features cover (room_builtin), check availability of the rest, and propose a substitute when a line is short.\nBRIEF: {\"end\": \"2026-11-18T06:30:00Z\", \"lines\": [{\"code\": \"MIC-WIRELESS\", \"quantity\": 2}, {\"code\": \"PROJ-PORTABLE\", \"quantity\": 1}], \"room_features\": [\"ac\", \"computers\", \"projector\", \"smart_board\"], \"room_id\": 8, \"start\": \"2026-11-18T03:30:00Z\"}"
      },
      "output": {
        "lines": [
          {
            "qty": 2,
            "source": "portable",
            "type_code": "MIC-WIRELESS"
          },
          {
            "qty": 0,
            "source": "room_builtin",
            "type_code": "PROJ-PORTABLE"
          }
        ],
        "unmet": [],
        "substitutions": []
      },
      "toolCalls": [
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "codes": [
              "MIC-WIRELESS",
              "PROJ-PORTABLE"
            ],
            "start": "2026-11-18T03:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7,
              "PROJ-PORTABLE": 5
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        }
      ]
    },
    {
      "sequence": 9,
      "agentName": "policy_cost",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 3,
      "input": {
        "task": "Price the chosen room and priced lines with calculate_quote, list the policy facts, and write a short officer summary.\nBRIEF: {\"attendees\": 45, \"budget_lkr\": \"8000.00\", \"builtin\": [\"PROJ-PORTABLE\"], \"duration_hours\": \"3.00\", \"end\": \"2026-11-18T06:30:00Z\", \"equipment_unmet\": [], \"policy\": {\"max_advance_days_lecturer\": 90, \"max_advance_days_student\": 60, \"max_capacity_ratio\": 3, \"max_duration_hours\": 8, \"max_open_requests\": 3, \"min_lead_time_hours\": 48}, \"priced_lines\": [{\"code\": \"MIC-WIRELESS\", \"quantity\": 2}], \"requester_role\": \"Student\", \"required_features\": [\"computers\", \"projector\"], \"room_capacity\": 60, \"room_code\": \"N201\", \"room_id\": 8, \"start\": \"2026-11-18T03:30:00Z\", \"substitutions\": [], \"venue_unmet\": null}"
      },
      "output": {
        "quote": {
          "lines": [
            {
              "qty": "3.00",
              "kind": "Room",
              "line_total": "4500.00",
              "unit_price": "1500.00",
              "description": "Computer lab N201, 3 h @ LKR 1,500"
            },
            {
              "qty": "2.00",
              "kind": "Equipment",
              "line_total": "1000.00",
              "unit_price": "500.00",
              "description": "Wireless microphone x2 @ LKR 500"
            }
          ],
          "total": "5500.00",
          "exempt": false,
          "currency": "LKR",
          "discount": "0.00",
          "subtotal": "5500.00",
          "discount_reason": null
        },
        "unmet": null,
        "policy_flags": [
          "Within budget: LKR 5,500.00 vs LKR 8,000.00",
          "Duration 3 h (at most 8 h)",
          "PROJ-PORTABLE provided by room N201 (not priced)"
        ],
        "officer_summary": "N201 fits 45 attendees (60 seats) with computers, projector. Equipment: 2 × MIC-WIRELESS; PROJ-PORTABLE provided by the room. Total LKR 5,500.00 (budget LKR 8,000.00): within budget."
      },
      "toolCalls": [
        {
          "toolName": "calculate_quote",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "start": "2026-11-18T03:30:00Z",
            "room_id": 8,
            "equipment": [
              {
                "code": "MIC-WIRELESS",
                "quantity": 2
              }
            ],
            "requester_role": "Student"
          },
          "resultSummary": {
            "lines": 2,
            "total": "5500.00",
            "exempt": false
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        }
      ]
    },
    {
      "sequence": 10,
      "agentName": "validate",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 13,
      "input": {
        "attempt": 2,
        "room_id": 8
      },
      "output": {
        "failed": [],
        "outcome": "pass"
      },
      "toolCalls": [
        {
          "toolName": "get_room_details",
          "args": {
            "room_id": 8
          },
          "resultSummary": {
            "id": 8,
            "code": "N201",
            "capacity": 60,
            "features": [
              "ac",
              "computers",
              "projector",
              "smart_board"
            ],
            "isActive": true
          },
          "succeeded": true,
          "error": null,
          "durationMs": 1
        },
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "start": "2026-11-18T03:30:00Z",
            "features": [],
            "page_size": 100,
            "building_id": 2,
            "max_capacity": 60,
            "min_capacity": 60
          },
          "resultSummary": {
            "rooms": [
              "8:N201"
            ],
            "total": 1
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "codes": [
              "MIC-WIRELESS",
              "PROJ-PORTABLE"
            ],
            "start": "2026-11-18T03:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7,
              "PROJ-PORTABLE": 5
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        },
        {
          "toolName": "calculate_quote",
          "args": {
            "end": "2026-11-18T06:30:00Z",
            "start": "2026-11-18T03:30:00Z",
            "room_id": 8,
            "equipment": [
              {
                "code": "MIC-WIRELESS",
                "quantity": 2
              }
            ],
            "requester_role": "Student"
          },
          "resultSummary": {
            "lines": 2,
            "total": "5500.00",
            "exempt": false
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "get_request_context",
          "args": {
            "request_id": 37
          },
          "resultSummary": {
            "notes": null,
            "status": "AgentProcessing",
            "hasClub": true,
            "attendees": 45,
            "requestId": 37,
            "requestedEnd": "2026-11-18T06:30:00Z",
            "requesterRole": "Student",
            "equipmentLines": 2,
            "requestedStart": "2026-11-18T03:30:00Z",
            "maxOpenRequests": 3,
            "openRequestCount": 2
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        }
      ]
    }
  ],
  "validation": [
    {
      "attempt": 2,
      "rules": [
        {
          "rule": "V01",
          "passed": true,
          "message": "4 outputs match their schemas (extra fields forbidden)"
        },
        {
          "rule": "V02",
          "passed": true,
          "message": "Room N201 exists and is still free for the window"
        },
        {
          "rule": "V03",
          "passed": true,
          "message": "60 seats for 45 attendees (at most 135)"
        },
        {
          "rule": "V04",
          "passed": true,
          "message": "Room N201 has computers, projector"
        },
        {
          "rule": "V05",
          "passed": true,
          "message": "Wed 09:00–12:00 is within 08:00–20:00, 3 h ≤ 8 h, on 30-minute boundaries"
        },
        {
          "rule": "V06",
          "passed": true,
          "message": "Starts ≥ 48 h from now and within 60 days (Student)"
        },
        {
          "rule": "V07",
          "passed": true,
          "message": "No blackout or booking overlaps room N201; public holidays are not checked (not implemented)"
        },
        {
          "rule": "V08",
          "passed": true,
          "message": "PROJ-PORTABLE provided by the room (projector); 2 × MIC-WIRELESS available (7)"
        },
        {
          "rule": "V09",
          "passed": true,
          "message": "Total LKR 5,500.00 equals the .NET recomputation"
        },
        {
          "rule": "V10",
          "passed": true,
          "message": "LKR 5,500.00 ≤ budget LKR 8,000.00"
        },
        {
          "rule": "V11",
          "passed": true,
          "message": "active club, registered rep; 2 other open requests < 3"
        },
        {
          "rule": "V12",
          "passed": true,
          "message": "1 room ids and 2 equipment codes came from tool results"
        }
      ]
    },
    {
      "attempt": 1,
      "rules": [
        {
          "rule": "V01",
          "passed": true,
          "message": "4 outputs match their schemas (extra fields forbidden)"
        },
        {
          "rule": "V02",
          "passed": true,
          "message": "Room A301 exists and is still free for the window"
        },
        {
          "rule": "V03",
          "passed": true,
          "message": "48 seats for 45 attendees (at most 135)"
        },
        {
          "rule": "V04",
          "passed": true,
          "message": "Room A301 has computers, projector"
        },
        {
          "rule": "V05",
          "passed": true,
          "message": "Wed 09:00–12:00 is within 08:00–20:00, 3 h ≤ 8 h, on 30-minute boundaries"
        },
        {
          "rule": "V06",
          "passed": true,
          "message": "Starts ≥ 48 h from now and within 60 days (Student)"
        },
        {
          "rule": "V07",
          "passed": true,
          "message": "No blackout or booking overlaps room A301; public holidays are not checked (not implemented)"
        },
        {
          "rule": "V08",
          "passed": true,
          "message": "PROJ-PORTABLE provided by the room (projector); 2 × MIC-WIRELESS available (7)"
        },
        {
          "rule": "V09",
          "passed": true,
          "message": "Total LKR 5,500.00 equals the .NET recomputation"
        },
        {
          "rule": "V10",
          "passed": true,
          "message": "LKR 5,500.00 ≤ budget LKR 8,000.00"
        },
        {
          "rule": "V11",
          "passed": true,
          "message": "active club, registered rep; 2 other open requests < 3"
        },
        {
          "rule": "V12",
          "passed": true,
          "message": "2 room ids and 2 equipment codes came from tool results"
        }
      ]
    }
  ],
  "decisions": [
    {
      "decision": "Revise",
      "officerName": "Mr. Perera",
      "comment": "Use a lab in the New Building",
      "decidedAt": "2026-09-29T06:15:01.637156Z"
    }
  ],
  "policySnapshot": {
    "opening_hours": {
      "fri": {
        "open": "08:00",
        "close": "20:00"
      },
      "mon": {
        "open": "08:00",
        "close": "20:00"
      },
      "sat": {
        "open": "08:00",
        "close": "16:00"
      },
      "sun": null,
      "thu": {
        "open": "08:00",
        "close": "20:00"
      },
      "tue": {
        "open": "08:00",
        "close": "20:00"
      },
      "wed": {
        "open": "08:00",
        "close": "20:00"
      }
    },
    "max_open_requests": 3,
    "max_capacity_ratio": 3,
    "max_duration_hours": 8,
    "min_lead_time_hours": 48,
    "checkout_window_minutes": 30,
    "free_cancellation_hours": 24,
    "max_advance_days_student": 60,
    "slot_granularity_minutes": 30,
    "max_advance_days_lecturer": 90
  },
  "policyChangedKeys": []
}

/** A run read after opening_hours changed. */
export const POLICY_CHANGED_RUN_DETAIL: AgentRunDetailDto = {
  "id": "b471ef61-ac1d-4b97-9e7d-bd675df77646",
  "requestId": 38,
  "revisionNo": 1,
  "status": "AwaitingApproval",
  "model": "stub",
  "nodes": [
    "supervisor",
    "venue_matching",
    "supervisor",
    "equipment_allocation",
    "supervisor",
    "policy_cost",
    "supervisor",
    "validate",
    "human_gate"
  ],
  "officerSummary": "A301 fits 45 attendees (48 seats) with computers, projector. Equipment: 2 × MIC-WIRELESS; PROJ-PORTABLE provided by the room. Total LKR 5,500.00 (budget LKR 8,000.00): within budget.",
  "failureReason": null,
  "createdAt": "2026-09-29T06:15:04.887542Z",
  "startedAt": "2026-09-29T06:15:04.894103Z",
  "completedAt": null,
  "durationMs": 1917,
  "proposal": {
    "chosen": {
      "roomId": 1,
      "code": "A301",
      "name": "Computer Lab A301",
      "capacity": 48,
      "building": "Main Building",
      "features": [
        "ac",
        "computers",
        "projector",
        "whiteboard"
      ],
      "reason": "48 seats for 45 attendees; has computers, projector; Main Building"
    },
    "alternatives": [
      {
        "roomId": 8,
        "code": "N201",
        "name": "Computer Lab N201",
        "capacity": 60,
        "building": "New Building",
        "features": [
          "ac",
          "computers",
          "projector",
          "smart_board"
        ],
        "reason": "60 seats for 45 attendees; has computers, projector; New Building"
      }
    ],
    "venueUnmet": null,
    "equipmentLines": [
      {
        "typeCode": "MIC-WIRELESS",
        "qty": 2,
        "source": "portable"
      },
      {
        "typeCode": "PROJ-PORTABLE",
        "qty": 0,
        "source": "room_builtin"
      }
    ],
    "substitutions": [],
    "equipmentUnmet": [],
    "policyFlags": [
      "Within budget: LKR 5,500.00 vs LKR 8,000.00",
      "Duration 3 h (at most 8 h)",
      "PROJ-PORTABLE provided by room A301 (not priced)"
    ]
  },
  "steps": [
    {
      "sequence": 1,
      "agentName": "supervisor",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 5,
      "input": {
        "revision": 1,
        "request_id": 38,
        "replan_reason": null
      },
      "output": {
        "steps": [
          {
            "task": "Find up to 3 FREE rooms that fit the attendees and have every required feature; rank them with a one-line reason each. Skip excluded rooms.",
            "agent": "venue_matching"
          },
          {
            "task": "For the chosen room, drop lines its features cover (room_builtin), check availability of the rest, and propose a substitute when a line is short.",
            "agent": "equipment_allocation"
          },
          {
            "task": "Price the chosen room and priced lines with calculate_quote, list the policy facts, and write a short officer summary.",
            "agent": "policy_cost"
          }
        ],
        "equipment": [
          {
            "quantity": 2,
            "type_code": "MIC-WIRELESS"
          },
          {
            "quantity": 1,
            "type_code": "PROJ-PORTABLE"
          }
        ],
        "planner_fallback": false,
        "soft_preferences": [],
        "required_features": [
          "computers",
          "projector"
        ]
      },
      "toolCalls": [
        {
          "toolName": "get_policy",
          "args": {},
          "resultSummary": {
            "keys": [
              "checkout_window_minutes",
              "free_cancellation_hours",
              "max_advance_days_lecturer",
              "max_advance_days_student",
              "max_capacity_ratio",
              "max_duration_hours",
              "max_open_requests",
              "min_lead_time_hours",
              "opening_hours",
              "slot_granularity_minutes"
            ]
          },
          "succeeded": true,
          "error": null,
          "durationMs": 1
        },
        {
          "toolName": "get_request_context",
          "args": {
            "request_id": 38
          },
          "resultSummary": {
            "notes": null,
            "status": "AgentProcessing",
            "hasClub": true,
            "attendees": 45,
            "requestId": 38,
            "requestedEnd": "2026-11-13T07:30:00Z",
            "requesterRole": "Student",
            "equipmentLines": 2,
            "requestedStart": "2026-11-13T04:30:00Z",
            "maxOpenRequests": 3,
            "openRequestCount": 1
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "list_feature_catalog",
          "args": {},
          "resultSummary": {
            "count": 6
          },
          "succeeded": true,
          "error": null,
          "durationMs": 0
        },
        {
          "toolName": "list_equipment_catalog",
          "args": {},
          "resultSummary": {
            "count": 10
          },
          "succeeded": true,
          "error": null,
          "durationMs": 0
        }
      ]
    },
    {
      "sequence": 2,
      "agentName": "venue_matching",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 3,
      "input": {
        "task": "Find up to 3 FREE rooms that fit the attendees and have every required feature; rank them with a one-line reason each. Skip excluded rooms.\nBRIEF: {\"attendees\": 45, \"end\": \"2026-11-13T07:30:00Z\", \"excluded_room_ids\": [], \"max_capacity_ratio\": 3, \"replan_reason\": null, \"required_features\": [\"computers\", \"projector\"], \"soft_preferences\": [], \"start\": \"2026-11-13T04:30:00Z\"}"
      },
      "output": {
        "unmet": null,
        "options": [
          {
            "code": "A301",
            "name": "Computer Lab A301",
            "reason": "48 seats for 45 attendees; has computers, projector; Main Building",
            "room_id": 1,
            "building": "Main Building",
            "capacity": 48,
            "features": [
              "ac",
              "computers",
              "projector",
              "whiteboard"
            ]
          },
          {
            "code": "N201",
            "name": "Computer Lab N201",
            "reason": "60 seats for 45 attendees; has computers, projector; New Building",
            "room_id": 8,
            "building": "New Building",
            "capacity": 60,
            "features": [
              "ac",
              "computers",
              "projector",
              "smart_board"
            ]
          }
        ]
      },
      "toolCalls": [
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-13T07:30:00Z",
            "start": "2026-11-13T04:30:00Z",
            "features": [
              "computers",
              "projector"
            ],
            "page_size": 100,
            "building_id": null,
            "max_capacity": null,
            "min_capacity": 45
          },
          "resultSummary": {
            "rooms": [
              "1:A301",
              "8:N201"
            ],
            "total": 2
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        }
      ]
    },
    {
      "sequence": 3,
      "agentName": "equipment_allocation",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 3,
      "input": {
        "task": "For the chosen room, drop lines its features cover (room_builtin), check availability of the rest, and propose a substitute when a line is short.\nBRIEF: {\"end\": \"2026-11-13T07:30:00Z\", \"lines\": [{\"code\": \"MIC-WIRELESS\", \"quantity\": 2}, {\"code\": \"PROJ-PORTABLE\", \"quantity\": 1}], \"room_features\": [\"ac\", \"computers\", \"projector\", \"whiteboard\"], \"room_id\": 1, \"start\": \"2026-11-13T04:30:00Z\"}"
      },
      "output": {
        "lines": [
          {
            "qty": 2,
            "source": "portable",
            "type_code": "MIC-WIRELESS"
          },
          {
            "qty": 0,
            "source": "room_builtin",
            "type_code": "PROJ-PORTABLE"
          }
        ],
        "unmet": [],
        "substitutions": []
      },
      "toolCalls": [
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-13T07:30:00Z",
            "codes": [
              "MIC-WIRELESS",
              "PROJ-PORTABLE"
            ],
            "start": "2026-11-13T04:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7,
              "PROJ-PORTABLE": 5
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        }
      ]
    },
    {
      "sequence": 4,
      "agentName": "policy_cost",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 2,
      "input": {
        "task": "Price the chosen room and priced lines with calculate_quote, list the policy facts, and write a short officer summary.\nBRIEF: {\"attendees\": 45, \"budget_lkr\": \"8000.00\", \"builtin\": [\"PROJ-PORTABLE\"], \"duration_hours\": \"3.00\", \"end\": \"2026-11-13T07:30:00Z\", \"equipment_unmet\": [], \"policy\": {\"max_advance_days_lecturer\": 90, \"max_advance_days_student\": 60, \"max_capacity_ratio\": 3, \"max_duration_hours\": 8, \"max_open_requests\": 3, \"min_lead_time_hours\": 48}, \"priced_lines\": [{\"code\": \"MIC-WIRELESS\", \"quantity\": 2}], \"requester_role\": \"Student\", \"required_features\": [\"computers\", \"projector\"], \"room_capacity\": 48, \"room_code\": \"A301\", \"room_id\": 1, \"start\": \"2026-11-13T04:30:00Z\", \"substitutions\": [], \"venue_unmet\": null}"
      },
      "output": {
        "quote": {
          "lines": [
            {
              "qty": "3.00",
              "kind": "Room",
              "line_total": "4500.00",
              "unit_price": "1500.00",
              "description": "Computer lab A301, 3 h @ LKR 1,500"
            },
            {
              "qty": "2.00",
              "kind": "Equipment",
              "line_total": "1000.00",
              "unit_price": "500.00",
              "description": "Wireless microphone x2 @ LKR 500"
            }
          ],
          "total": "5500.00",
          "exempt": false,
          "currency": "LKR",
          "discount": "0.00",
          "subtotal": "5500.00",
          "discount_reason": null
        },
        "unmet": null,
        "policy_flags": [
          "Within budget: LKR 5,500.00 vs LKR 8,000.00",
          "Duration 3 h (at most 8 h)",
          "PROJ-PORTABLE provided by room A301 (not priced)"
        ],
        "officer_summary": "A301 fits 45 attendees (48 seats) with computers, projector. Equipment: 2 × MIC-WIRELESS; PROJ-PORTABLE provided by the room. Total LKR 5,500.00 (budget LKR 8,000.00): within budget."
      },
      "toolCalls": [
        {
          "toolName": "calculate_quote",
          "args": {
            "end": "2026-11-13T07:30:00Z",
            "start": "2026-11-13T04:30:00Z",
            "room_id": 1,
            "equipment": [
              {
                "code": "MIC-WIRELESS",
                "quantity": 2
              }
            ],
            "requester_role": "Student"
          },
          "resultSummary": {
            "lines": 2,
            "total": "5500.00",
            "exempt": false
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        }
      ]
    },
    {
      "sequence": 5,
      "agentName": "validate",
      "status": "Succeeded",
      "retries": 0,
      "error": null,
      "durationMs": 11,
      "input": {
        "attempt": 1,
        "room_id": 1
      },
      "output": {
        "failed": [],
        "outcome": "pass"
      },
      "toolCalls": [
        {
          "toolName": "get_room_details",
          "args": {
            "room_id": 1
          },
          "resultSummary": {
            "id": 1,
            "code": "A301",
            "capacity": 48,
            "features": [
              "ac",
              "computers",
              "projector",
              "whiteboard"
            ],
            "isActive": true
          },
          "succeeded": true,
          "error": null,
          "durationMs": 1
        },
        {
          "toolName": "search_available_rooms",
          "args": {
            "end": "2026-11-13T07:30:00Z",
            "start": "2026-11-13T04:30:00Z",
            "features": [],
            "page_size": 100,
            "building_id": 1,
            "max_capacity": 48,
            "min_capacity": 48
          },
          "resultSummary": {
            "rooms": [
              "1:A301"
            ],
            "total": 1
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "check_equipment_availability",
          "args": {
            "end": "2026-11-13T07:30:00Z",
            "codes": [
              "MIC-WIRELESS",
              "PROJ-PORTABLE"
            ],
            "start": "2026-11-13T04:30:00Z"
          },
          "resultSummary": {
            "available": {
              "MIC-WIRELESS": 7,
              "PROJ-PORTABLE": 5
            }
          },
          "succeeded": true,
          "error": null,
          "durationMs": 3
        },
        {
          "toolName": "calculate_quote",
          "args": {
            "end": "2026-11-13T07:30:00Z",
            "start": "2026-11-13T04:30:00Z",
            "room_id": 1,
            "equipment": [
              {
                "code": "MIC-WIRELESS",
                "quantity": 2
              }
            ],
            "requester_role": "Student"
          },
          "resultSummary": {
            "lines": 2,
            "total": "5500.00",
            "exempt": false
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        },
        {
          "toolName": "get_request_context",
          "args": {
            "request_id": 38
          },
          "resultSummary": {
            "notes": null,
            "status": "AgentProcessing",
            "hasClub": true,
            "attendees": 45,
            "requestId": 38,
            "requestedEnd": "2026-11-13T07:30:00Z",
            "requesterRole": "Student",
            "equipmentLines": 2,
            "requestedStart": "2026-11-13T04:30:00Z",
            "maxOpenRequests": 3,
            "openRequestCount": 1
          },
          "succeeded": true,
          "error": null,
          "durationMs": 2
        }
      ]
    }
  ],
  "validation": [
    {
      "attempt": 1,
      "rules": [
        {
          "rule": "V01",
          "passed": true,
          "message": "4 outputs match their schemas (extra fields forbidden)"
        },
        {
          "rule": "V02",
          "passed": true,
          "message": "Room A301 exists and is still free for the window"
        },
        {
          "rule": "V03",
          "passed": true,
          "message": "48 seats for 45 attendees (at most 135)"
        },
        {
          "rule": "V04",
          "passed": true,
          "message": "Room A301 has computers, projector"
        },
        {
          "rule": "V05",
          "passed": true,
          "message": "Fri 10:00–13:00 is within 08:00–20:00, 3 h ≤ 8 h, on 30-minute boundaries"
        },
        {
          "rule": "V06",
          "passed": true,
          "message": "Starts ≥ 48 h from now and within 60 days (Student)"
        },
        {
          "rule": "V07",
          "passed": true,
          "message": "No blackout or booking overlaps room A301; public holidays are not checked (not implemented)"
        },
        {
          "rule": "V08",
          "passed": true,
          "message": "PROJ-PORTABLE provided by the room (projector); 2 × MIC-WIRELESS available (7)"
        },
        {
          "rule": "V09",
          "passed": true,
          "message": "Total LKR 5,500.00 equals the .NET recomputation"
        },
        {
          "rule": "V10",
          "passed": true,
          "message": "LKR 5,500.00 ≤ budget LKR 8,000.00"
        },
        {
          "rule": "V11",
          "passed": true,
          "message": "active club, registered rep; 1 other open requests < 3"
        },
        {
          "rule": "V12",
          "passed": true,
          "message": "2 room ids and 2 equipment codes came from tool results"
        }
      ]
    }
  ],
  "decisions": [],
  "policySnapshot": {
    "opening_hours": {
      "fri": {
        "open": "08:00",
        "close": "20:00"
      },
      "mon": {
        "open": "08:00",
        "close": "20:00"
      },
      "sat": {
        "open": "08:00",
        "close": "16:00"
      },
      "sun": null,
      "thu": {
        "open": "08:00",
        "close": "20:00"
      },
      "tue": {
        "open": "08:00",
        "close": "20:00"
      },
      "wed": {
        "open": "08:00",
        "close": "20:00"
      }
    },
    "max_open_requests": 3,
    "max_capacity_ratio": 3,
    "max_duration_hours": 8,
    "min_lead_time_hours": 48,
    "checkout_window_minutes": 30,
    "free_cancellation_hours": 24,
    "max_advance_days_student": 60,
    "slot_granularity_minutes": 30,
    "max_advance_days_lecturer": 90
  },
  "policyChangedKeys": [
    "opening_hours"
  ]
}

/** Approve 409: the room was blacked out after the proposal. */
export const CONFLICT_NEW_PROPOSAL: ProblemBody = {
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.10",
  "title": "The proposal is no longer valid: Final re-check failed: V02: Room A301 is no longer free for the requested window. A new proposal is being prepared.",
  "status": 409,
  "traceId": "0f0a41f6bff8a8cf7a8478fdbed1bfff"
}

/** Approve 409: the advance window shrank after the proposal. */
export const CONFLICT_TIME_CLOSED: ProblemBody = {
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.10",
  "title": "The requested time is no longer valid: Can be booked at most 30 days ahead (as of submission). The request was closed; the requester can submit a new time.",
  "status": 409,
  "traceId": "0e5f5d2ed7bc74f900a105c8fc9787b1"
}

/** retry-agent 409 on an approved request. */
export const RETRY_NOT_RESTARTABLE: ProblemBody = {
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.10",
  "title": "Only a failed or not-yet-started request can be (re)started",
  "status": 409,
  "traceId": "52f7484dcd95dde80fb57323ef477912"
}
