// <auto-generated />
using System;
using System.Collections.Generic;
using CampusSpace.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace CampusSpace.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927124619_AddBookingRequests")]
    partial class AddBookingRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CampusSpace.Api.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.BookingRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attendees")
                        .HasColumnType("integer");

                    b.Property<decimal>("BudgetLkr")
                        .HasColumnType("numeric(10,2)");

                    b.Property<long?>("ClubId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RequestedEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RequesterId")
                        .HasColumnType("bigint");

                    b.Property<List<string>>("RequiredFeatures")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("RequesterId", "Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("BookingRequests", t =>
                        {
                            t.HasCheckConstraint("CK_BookingRequests_Attendees", "\"Attendees\" BETWEEN 1 AND 2000");

                            t.HasCheckConstraint("CK_BookingRequests_BudgetLkr", "\"BudgetLkr\" >= 0");

                            t.HasCheckConstraint("CK_BookingRequests_Purpose_NotBlank", "btrim(\"Purpose\") <> ''");

                            t.HasCheckConstraint("CK_BookingRequests_RequestedEnd_After_Start", "\"RequestedEnd\" > \"RequestedStart\"");

                            t.HasCheckConstraint("CK_BookingRequests_Status", "\"Status\" IN ('Submitted', 'AgentProcessing', 'PendingApproval', 'Approved', 'Completed', 'AgentFailed', 'RevisionRequested', 'Rejected', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Building", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Buildings", t =>
                        {
                            t.HasCheckConstraint("CK_Buildings_Code_Format", "\"Code\" ~ '^[A-Z0-9][A-Z0-9-]*$'");

                            t.HasCheckConstraint("CK_Buildings_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Club", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clubs", t =>
                        {
                            t.HasCheckConstraint("CK_Clubs_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.ClubMember", b =>
                {
                    b.Property<long>("ClubId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClubId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ClubId" }, "IX_ClubMembers_OneRepresentative")
                        .IsUnique()
                        .HasFilter("\"IsRepresentative\"");

                    b.ToTable("ClubMembers");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("TypeId", "Status");

                    b.ToTable("EquipmentItems", t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentItems_AssetTag_NotBlank", "btrim(\"AssetTag\") <> ''");

                            t.HasCheckConstraint("CK_EquipmentItems_Condition", "\"Condition\" IN ('Good', 'MinorWear', 'Damaged')");

                            t.HasCheckConstraint("CK_EquipmentItems_Status", "\"Status\" IN ('Available', 'OnLoan', 'UnderRepair', 'Retired')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentSubstitute", b =>
                {
                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubstituteTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TypeId", "SubstituteTypeId");

                    b.HasIndex("SubstituteTypeId");

                    b.ToTable("EquipmentSubstitutes", t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentSubstitutes_NotSelf", "\"TypeId\" <> \"SubstituteTypeId\"");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("CoveredByFeatureCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FeePerBooking")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CoveredByFeatureCode");

                    b.ToTable("EquipmentTypes", t =>
                        {
                            t.HasCheckConstraint("CK_EquipmentTypes_Category", "\"Category\" IN ('Audio', 'Visual', 'Computing', 'Presentation', 'Accessory')");

                            t.HasCheckConstraint("CK_EquipmentTypes_Code_Format", "\"Code\" ~ '^[A-Z0-9]+(-[A-Z0-9]+)*$' AND char_length(\"Code\") >= 2");

                            t.HasCheckConstraint("CK_EquipmentTypes_FeePerBooking", "\"FeePerBooking\" >= 0");

                            t.HasCheckConstraint("CK_EquipmentTypes_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Features", t =>
                        {
                            t.HasCheckConstraint("CK_Features_Code_Format", "\"Code\" ~ '^[a-z][a-z0-9]*(_[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_Features_Name_NotBlank", "btrim(\"Name\") <> ''");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.PolicySetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PolicySettings", t =>
                        {
                            t.HasCheckConstraint("CK_PolicySettings_Key", "\"Key\" IN ('opening_hours', 'min_lead_time_hours', 'max_advance_days_student', 'max_advance_days_lecturer', 'max_duration_hours', 'max_capacity_ratio', 'slot_granularity_minutes', 'free_cancellation_hours', 'max_open_requests')");

                            t.HasCheckConstraint("CK_PolicySettings_ValueType", "\"ValueType\" IN ('int', 'decimal', 'bool', 'json')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.PricingRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsExempt")
                        .HasColumnType("boolean");

                    b.Property<string>("RequesterRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoomType", "RequesterRole", "ValidFrom" }, "IX_PricingRules_RoomType_RequesterRole_ValidFrom")
                        .IsUnique();

                    b.ToTable("PricingRules", t =>
                        {
                            t.HasCheckConstraint("CK_PricingRules_Exempt_ZeroRate", "NOT \"IsExempt\" OR \"HourlyRate\" = 0");

                            t.HasCheckConstraint("CK_PricingRules_HourlyRate", "\"HourlyRate\" >= 0");

                            t.HasCheckConstraint("CK_PricingRules_RequesterRole", "\"RequesterRole\" IN ('Student', 'Lecturer')");

                            t.HasCheckConstraint("CK_PricingRules_RoomType", "\"RoomType\" IN ('LectureHall', 'ComputerLab', 'SeminarRoom', 'Auditorium')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RequestStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ChangedById")
                        .HasColumnType("bigint");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("RequestId", "ChangedAt");

                    b.ToTable("RequestStatusHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_RequestStatusHistory_FromStatus", "\"FromStatus\" IS NULL OR \"FromStatus\" IN ('Submitted', 'AgentProcessing', 'PendingApproval', 'Approved', 'Completed', 'AgentFailed', 'RevisionRequested', 'Rejected', 'Cancelled')");

                            t.HasCheckConstraint("CK_RequestStatusHistory_ToStatus", "\"ToStatus\" IN ('Submitted', 'AgentProcessing', 'PendingApproval', 'Approved', 'Completed', 'AgentFailed', 'RevisionRequested', 'Rejected', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RequestedEquipmentLine", b =>
                {
                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("RequestId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("RequestedEquipmentLines", t =>
                        {
                            t.HasCheckConstraint("CK_RequestedEquipmentLines_Quantity", "\"Quantity\" BETWEEN 1 AND 50");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BuildingId")
                        .HasColumnType("bigint");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("Capacity");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Rooms", t =>
                        {
                            t.HasCheckConstraint("CK_Rooms_Capacity", "\"Capacity\" > 0");

                            t.HasCheckConstraint("CK_Rooms_Code_NotBlank", "btrim(\"Code\") <> ''");

                            t.HasCheckConstraint("CK_Rooms_Name_NotBlank", "btrim(\"Name\") <> ''");

                            t.HasCheckConstraint("CK_Rooms_Type", "\"Type\" IN ('LectureHall', 'ComputerLab', 'SeminarRoom', 'Auditorium')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RoomBlackout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<NpgsqlRange<DateTime>>("TimeRange")
                        .HasColumnType("tstzrange");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex(new[] { "RoomId", "TimeRange" }, "IX_RoomBlackouts_RoomId_TimeRange");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "RoomId", "TimeRange" }, "IX_RoomBlackouts_RoomId_TimeRange"), "gist");

                    b.ToTable("RoomBlackouts", t =>
                        {
                            t.HasCheckConstraint("CK_RoomBlackouts_Reason_NotBlank", "btrim(\"Reason\") <> ''");

                            t.HasCheckConstraint("CK_RoomBlackouts_TimeRange", "NOT isempty(\"TimeRange\") AND NOT lower_inf(\"TimeRange\") AND NOT upper_inf(\"TimeRange\") AND lower_inc(\"TimeRange\") AND NOT upper_inc(\"TimeRange\")");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RoomFeature", b =>
                {
                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<long>("FeatureId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoomId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("RoomFeatures");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Student', 'Lecturer', 'LabTechnician', 'FacilitiesOfficer', 'Admin')");
                        });
                });

            modelBuilder.Entity("CampusSpace.Api.Models.AuditLog", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.BookingRequest", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampusSpace.Api.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.ClubMember", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Club", "Club")
                        .WithMany("Members")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentItem", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.EquipmentType", "Type")
                        .WithMany("Items")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentSubstitute", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.EquipmentType", "SubstituteType")
                        .WithMany()
                        .HasForeignKey("SubstituteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.EquipmentType", "Type")
                        .WithMany("Substitutes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubstituteType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentType", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Feature", "CoveredByFeature")
                        .WithMany()
                        .HasForeignKey("CoveredByFeatureCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoveredByFeature");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.PolicySetting", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RequestStatusHistory", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampusSpace.Api.Models.BookingRequest", "Request")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RequestedEquipmentLine", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.BookingRequest", "Request")
                        .WithMany("EquipmentLines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.EquipmentType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Room", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RoomBlackout", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.Room", "Room")
                        .WithMany("Blackouts")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.RoomFeature", b =>
                {
                    b.HasOne("CampusSpace.Api.Models.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusSpace.Api.Models.Room", "Room")
                        .WithMany("RoomFeatures")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.BookingRequest", b =>
                {
                    b.Navigation("EquipmentLines");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Club", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.EquipmentType", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Substitutes");
                });

            modelBuilder.Entity("CampusSpace.Api.Models.Room", b =>
                {
                    b.Navigation("Blackouts");

                    b.Navigation("RoomFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
